# Generated by Django 5.2.16 on 2026-08-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(help_text='Identificador de la categoría', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Nombre de la categoría', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción de la categoría', max_length=500)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.CharField(help_text='Identificador de la clase de producto', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Nombre de la clase de producto', max_length=255)),
                ('product_category', models.ForeignKey(blank=True, help_text='Categoría de la clase de producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_classes', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Clase de producto',
                'verbose_name_plural': 'Clases de producto',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='Identificador del producto', max_length=255, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, help_text='Código de barras del producto', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='Nombre del producto', max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Costo del producto', max_digits=14, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del producto', max_digits=14, null=True)),
                ('unit_of_measure', models.CharField(blank=True, help_text='Unidad de medida del producto', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está activo')),
                ('product_class', models.ForeignKey(blank=True, help_text='Clase del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productclass')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, default='', help_text='Número o identificador del lote', max_length=100)),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de expiración del lote', null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad en stock', max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='products.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='sales.warehouse')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'indexes': [models.Index(fields=['expiration_date'], name='products_st_expirat_aa8ed7_idx'), models.Index(fields=['warehouse', 'expiration_date'], name='products_st_warehou_1e78fa_idx'), models.Index(fields=['product', 'warehouse'], name='products_st_product_6d36e8_idx'), models.Index(fields=['lot_number'], name='products_st_lot_num_ee11e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse', 'lot_number'), name='unique_stock_product_warehouse_lot')],
            },
        ),
    ]
