# Generated by Django 5.2.16 on 2026-08-17 02:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.CharField(help_text='Identificador de la propiedad (ej: SUSTANCIA_ACTIVA, LABORATORIO)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la propiedad', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción de la propiedad', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Propiedad de producto',
                'verbose_name_plural': 'Propiedades de producto',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Costo del producto', max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Precio del producto', max_digits=14),
        ),
        migrations.CreateModel(
            name='ProductPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Valor de la propiedad', max_length=500)),
                ('product', models.ForeignKey(help_text='Producto asociado', on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='products.product')),
                ('property', models.ForeignKey(help_text='Propiedad asignada', on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='products.productproperty')),
            ],
            options={
                'verbose_name': 'Valor de propiedad',
                'verbose_name_plural': 'Valores de propiedades',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(blank=True, help_text='Propiedades del producto', related_name='products', through='products.ProductPropertyValue', to='products.productproperty'),
        ),
        migrations.AddIndex(
            model_name='productpropertyvalue',
            index=models.Index(fields=['property', 'value'], name='products_pr_propert_03162d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productpropertyvalue',
            constraint=models.UniqueConstraint(fields=('product', 'property'), name='unique_product_property'),
        ),
    ]
