# Generated by Django 5.2.16 on 2026-08-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productproperty_alter_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='Código de barras del producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Nombre del producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='', help_text='Unidad de medida del producto', max_length=255),
        ),
    ]
