# Generated by Django 6.0.5 on 2026-07-22 01:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0023_alter_accountsreceivable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, help_text='Folio Fiscal UUID del SAT', null=True, unique=True)),
                ('serie', models.CharField(blank=True, help_text='Serie del CFDI', max_length=25, null=True)),
                ('folio', models.CharField(blank=True, help_text='Folio del CFDI', max_length=25, null=True)),
                ('date', models.DateTimeField(help_text='Fecha de expedición del CFDI')),
                ('cfdi_type', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('P', 'Pago'), ('T', 'Traslado'), ('N', 'Nómina')], default='I', help_text='Tipo de comporbante', max_length=1)),
                ('payment_form', models.CharField(help_text='Forma de pago (ej. 01, 03)', max_length=3)),
                ('payment_method', models.CharField(help_text='Método de pago (PUE, PPD)', max_length=3)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('exportation', models.CharField(default='01', max_length=2)),
                ('expedition_place', models.CharField(help_text='Código postal de expedición', max_length=5)),
                ('receiver_rfc', models.CharField(help_text='RFC del receptor', max_length=13)),
                ('receiver_name', models.CharField(help_text='Nombre o razón social del receptor', max_length=255)),
                ('receiver_cfdi_use', models.CharField(help_text='Uso CFDI (ej. G03)', max_length=3)),
                ('receiver_fiscal_regime', models.CharField(help_text='Régimen fiscal del receptor', max_length=3)),
                ('receiver_zip_code', models.CharField(help_text='Código postal del receptor', max_length=5)),
                ('issuer_rfc', models.CharField(help_text='RFC del emisor', max_length=13)),
                ('issuer_name', models.CharField(help_text='Nombre o razón social del emisor', max_length=255)),
                ('issuer_fiscal_regime', models.CharField(help_text='Régimen fiscal del emisor', max_length=3)),
                ('issuer_zip_code', models.CharField(help_text='Código postal del emisor', max_length=5)),
                ('subtotal', models.DecimalField(decimal_places=6, help_text='Subtotal general', max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=0, help_text='Descuento general', max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, help_text='Total general', max_digits=18)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('cancelado', 'Cancelado')], default='vigente', max_length=20)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='invoices/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('api_response', models.JSONField(blank=True, help_text='Respuesta completa de la API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación (del registro)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización (del registro)')),
            ],
            options={
                'verbose_name': 'Factura (CFDI)',
                'verbose_name_plural': 'Facturas (CFDI)',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='Clave de producto o servicio del SAT (ej. 10111302)', max_length=10)),
                ('identification_number', models.CharField(blank=True, help_text='No. Identificación o SKU interno', max_length=50, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('unit_code', models.CharField(help_text='Clave de unidad del SAT (ej. H87)', max_length=5)),
                ('unit_name', models.CharField(help_text='Descripción de la unidad (ej. Pieza)', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=6, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tax_object', models.CharField(help_text='ObjetoImp (01, 02, 03)', max_length=2)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'Concepto de factura',
                'verbose_name_plural': 'Conceptos de factura',
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='IVA, ISR, IEPS', max_length=10)),
                ('is_retention', models.BooleanField(default=False)),
                ('is_federal_tax', models.BooleanField(default=True)),
                ('base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('total', models.DecimalField(decimal_places=6, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sales.invoiceitem')),
            ],
            options={
                'verbose_name': 'Impuesto de factura',
                'verbose_name_plural': 'Impuestos de factura',
                'db_table': 'invoice_item_taxes',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, help_text='Referencia unica de la venta, conformado por la fecha de emisión y la secuencia de ventas del día. Ejemplo: 20260720_123', max_length=255, unique=True)),
                ('sale_date', models.DateTimeField(db_index=True, help_text='Fecha y hora en la que se realizó la venta')),
                ('sale_status', models.CharField(choices=[('completed', 'Completada'), ('pending', 'Pendiente'), ('canceled', 'Cancelada')], db_index=True, default='pending', help_text='Estado de la venta', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagada'), ('partially_paid', 'Parcialmente pagada'), ('canceled', 'Cancelada')], db_index=True, default='pending', help_text='Estado del pago', max_length=20)),
                ('currency', models.CharField(default='MXN', help_text='Divisa en la que se realizó la venta', max_length=3)),
                ('currency_exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Valor de la divisa', max_digits=10)),
                ('payment_form', models.CharField(choices=[('01', '01 Efectivo'), ('02', '02 Cheque nominativo'), ('03', '03 Transferencia electrónica de fondos'), ('04', '04 Tarjeta de crédito'), ('05', '05 Monedero electrónico'), ('06', '06 Dinero electrónico'), ('08', '08 Vales de despensa'), ('12', '12 Dación en pago'), ('13', '13 Pago por subrogación'), ('14', '14 Pago por consignación'), ('15', '15 Condonación'), ('17', '17 Compensación'), ('23', '23 Novación'), ('24', '24 Confusión'), ('25', '25 Remisión de deuda'), ('26', '26 Prescripción o caducidad'), ('27', '27 A satisfacción del acreedor'), ('28', '28 Tarjeta de débito'), ('29', '29 Tarjeta de servicios'), ('30', '30 Aplicación de anticipos'), ('31', '31 Intermediario pago'), ('99', '99 Por definir')], default='99', help_text='Forma de pago', max_length=2)),
                ('payment_method', models.CharField(choices=[('PUE', 'PUE Pago en una sola exhibición'), ('PPD', 'PPD Pago en parcialidades o diferido')], default='PUE', help_text='Método de pago', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, help_text='Subtotal de la venta sin impuestos ni descuentos', max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=0, help_text='Descuento aplicado a la venta', max_digits=18)),
                ('taxes', models.DecimalField(decimal_places=6, default=0, help_text='Impuestos aplicados a la venta', max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, help_text='Total de la venta con impuestos y descuentos', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Cliente que realizó la compra', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Documento fiscal CFDI asociado a esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.invoice')),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Asiento contable generado por esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='accounting.journalentry')),
                ('route', models.ForeignKey(blank=True, help_text='Ruta/vendedor asignado a esta venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.route')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Lugar de expedición de la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Cantidad de producto vendido', max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, help_text='Precio unitario del producto', max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Costo del producto al momento de vender para asiento de Costo de Ventas', max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=0, help_text='Descuento aplicado al producto', max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, help_text='Subtotal de la línea sin impuestos ni descuentos', max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('description_override', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='core.product')),
                ('sale', models.ForeignKey(help_text='Venta a la que pertenece esta línea', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Desglose de venta',
                'verbose_name_plural': 'Desgloses de ventas',
                'db_table': 'sales_lines',
            },
        ),
        migrations.CreateModel(
            name='SaleLineTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('IVA', 'IVA'), ('ISR', 'ISR'), ('IEPS', 'IEPS')], default='IVA', max_length=10)),
                ('factor_type', models.CharField(choices=[('Tasa', 'Tasa'), ('Cuota', 'Cuota'), ('Exento', 'Exento')], default='Tasa', max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Ej: 0.1600 para 16%', max_digits=6)),
                ('base', models.DecimalField(decimal_places=6, help_text='Base gravable', max_digits=18)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Monto final del impuesto', max_digits=18)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sales.saleline')),
                ('tax_account', models.ForeignKey(blank=True, help_text='Cuenta contable asociada (ej. 209.01 IVA Pendiente de Trasladar)', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
            ],
            options={
                'verbose_name': 'Impuesto de desglose de venta',
                'verbose_name_plural': 'Impuestos de desgloses de ventas',
                'db_table': 'sales_line_taxes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('01', '01 Nota de crédito'), ('02', '02 Nota de débito'), ('03', '03 Devolución de mercancía'), ('04', '04 Sustitución de los CFDI previos'), ('05', '05 Traslados de mercancías facturados previamente'), ('06', '06 Factura generada por los traslados previos'), ('07', '07 CFDI por aplicación de anticipo'), ('08', '08 Factura generada por pagos en parcialidades'), ('09', '09 Factura generada por pagos diferidos')], help_text='Tipo de relación SAT (ej. 04 para Sustitución)', max_length=2)),
                ('source_invoice', models.ForeignKey(help_text='CFDI que se está emitiendo (Hijo)', on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='sales.invoice')),
                ('target_invoice', models.ForeignKey(help_text='CFDI previo relacionado (Padre)', on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'CFDI Relacionado',
                'verbose_name_plural': 'CFDIs Relacionados',
                'db_table': 'invoice_relations',
                'unique_together': {('source_invoice', 'target_invoice', 'relation_type')},
            },
        ),
    ]
