# Generated by Django 5.2.16 on 2026-08-16 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0004_monitoringformschedule_week_of_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.CharField(help_text='Identificador del tipo de ruta', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del tipo de ruta', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de ruta', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de ruta',
                'verbose_name_plural': 'Tipos de ruta',
            },
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.CharField(help_text='Identificador único del canal de venta', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del canal de venta', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del canal de venta', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Canal de venta',
                'verbose_name_plural': 'Canales de venta',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.CharField(help_text='Identificador del centro de distribución', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del centro de distribución', max_length=50, unique=True)),
                ('warehouse_type', models.CharField(choices=[('warehouse', 'almacén'), ('retail', 'tienda'), ('transfer', 'traspaso'), ('damaged', 'dañado/merma')], default='warehouse', help_text='Tipo de centro de distribución', max_length=20)),
            ],
            options={
                'verbose_name': 'Centro de distribución',
                'verbose_name_plural': 'Centros de distribución',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(help_text='Identificador de la ruta.', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la ruta. No necesariamente relacionado con el nombre del vendedor', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la ruta', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Indica si la ruta es apta para asignación a un colaborador o esta operando')),
                ('business_unit', models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece la ruta. No necesariamente asociada a la unidad de negocio del colaborador que opera la ruta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='human_resources.businessunit')),
                ('route_type', models.ForeignKey(help_text='Tipo de ruta', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='sales.routetype')),
                ('sale_channel', models.ForeignKey(help_text='Canal de venta asociado a la ruta', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='sales.salechannel')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='Fecha de inicio de la asignación')),
                ('date_end', models.DateField(blank=True, help_text='Fecha de fin de la asignación', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la asignación', null=True)),
                ('employee', models.ForeignKey(help_text='Colaborador asignado', on_delete=django.db.models.deletion.PROTECT, related_name='route_assignments', to='human_resources.employee')),
                ('route', models.ForeignKey(help_text='Ruta asignada', on_delete=django.db.models.deletion.PROTECT, related_name='route_assignments', to='sales.route')),
            ],
            options={
                'verbose_name': 'Asignación de ruta',
                'verbose_name_plural': 'Asignaciones de ruta',
                'constraints': [models.UniqueConstraint(fields=('route', 'employee', 'date_start'), name='sales_unique_route_assignment'), models.UniqueConstraint(condition=models.Q(('date_end__isnull', True)), fields=('route',), name='sales_unique_active_assignment_per_route')],
            },
        ),
        migrations.CreateModel(
            name='UserRouteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, help_text='Indica si el usuario puede ver la ruta y su información relacionada')),
                ('can_edit', models.BooleanField(default=False, help_text='Indica si el usuario puede editar la ruta y su información relacionada')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el acceso del usuario a la ruta', null=True)),
                ('route', models.ForeignKey(help_text='Ruta a la que el usuario tiene acceso', on_delete=django.db.models.deletion.CASCADE, to='sales.route')),
                ('user', models.ForeignKey(help_text='Usuario que tiene acceso a la ruta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso de usuario a ruta',
                'verbose_name_plural': 'Accesos de usuarios a rutas',
                'constraints': [models.UniqueConstraint(fields=('user', 'route'), name='sales_unique_user_route_access')],
            },
        ),
    ]
