# Generated by Django 6.0.5 on 2026-07-24 06:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('human_resources', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.CharField(help_text='Identificador único del tipo de ruta', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del tipo de ruta', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de ruta', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de ruta',
                'verbose_name_plural': 'Tipos de ruta',
            },
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.CharField(help_text='Identificador único del canal de venta', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del canal de venta', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del canal de venta', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Canal de venta',
                'verbose_name_plural': 'Canales de venta',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la ruta.', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la ruta. No necesariamente relacionado con el nombre del vendedor', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la ruta', null=True)),
                ('warehouse', models.ForeignKey(help_text='Centro de distribución asociado a la ruta', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_routes', to='inventory.warehouse')),
                ('route_type', models.ForeignKey(help_text='Tipo de ruta', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_routes', to='sales.routetype')),
                ('sale_channel', models.ForeignKey(help_text='Canal de venta asociado a la ruta', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_routes', to='sales.salechannel')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la venta. Formato serie_aaaammdd_consecutivo', max_length=50, primary_key=True, serialize=False)),
                ('sale_status', models.CharField(choices=[('quoted', 'cotizada'), ('completed', 'completada'), ('cancelled', 'cancelada')], default='quoted', help_text='Estado de la venta', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'pendiente'), ('paid', 'pagada'), ('refunded', 'reembolsada')], default='pending', help_text='Estado del pago de la venta', max_length=20)),
                ('sale_date', models.DateTimeField(help_text='Fecha y hora de la venta')),
                ('subtotal', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Subtotal de la venta (Monto sin considerar impuestos ni descuentos)', max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Descuento de la venta (aplicado al subtotal)', max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total de impuestos de la venta (aplicado al subtotal)', max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total de la venta (Subtotal - Descuento + Total de impuestos)', max_digits=18)),
                ('notes', models.TextField(blank=True, help_text='Notas generales o comentarios', null=True)),
                ('customer', models.ForeignKey(help_text='Cliente asociado a la venta', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_sales', to='customers.customer')),
                ('route', models.ForeignKey(help_text='Ruta asignada a la venta', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_sales', to='sales.route')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1.00'), help_text='Cantidad vendida', max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Precio unitario del producto', max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Costo unitario del producto', max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Subtotal de la línea (Monto sin considerar impuestos ni descuentos)', max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Descuento de la línea (aplicado al subtotal)', max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total de impuestos de la línea (aplicado al subtotal)', max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total de la línea (Subtotal - Descuento + Total de impuestos)', max_digits=18)),
                ('sale', models.ForeignKey(help_text='Venta asociada a la línea', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_lines', to='sales.sale')),
                ('variant', models.ForeignKey(help_text='Variante del producto vendido', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_sale_lines', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Línea de venta',
                'verbose_name_plural': 'Líneas de venta',
            },
        ),
        migrations.CreateModel(
            name='SaleLineTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('IVA', 'IVA'), ('ISR', 'ISR'), ('IEPS', 'IEPS')], default='IVA', help_text='Tipo de impuesto', max_length=20)),
                ('tax_factor_type', models.CharField(choices=[('Tasa', 'Tasa'), ('Cuota', 'Cuota'), ('Exento', 'Exento')], default='Tasa', help_text='Tipo de factor de impuesto', max_length=20)),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Tasa o cuota del impuesto. Ej: 0.16 para 16%', max_digits=10)),
                ('base', models.DecimalField(decimal_places=6, help_text='Base gravable', max_digits=18)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Monto del impuesto', max_digits=18)),
                ('sale_line', models.ForeignKey(help_text='Línea de venta asociada al impuesto', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_taxes', to='sales.saleline')),
            ],
            options={
                'verbose_name': 'Impuesto de línea de venta',
                'verbose_name_plural': 'Impuestos de líneas de venta',
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='Fecha de inicio de la asignación')),
                ('date_end', models.DateField(blank=True, help_text='Fecha de fin de la asignación', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la asignación', null=True)),
                ('employee', models.ForeignKey(help_text='Colaborador asignado', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_route_assignments', to='human_resources.employee')),
                ('route', models.ForeignKey(help_text='Ruta asignada', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_route_assignments', to='sales.route')),
            ],
            options={
                'verbose_name': 'Asignación de ruta',
                'verbose_name_plural': 'Asignaciones de ruta',
                'constraints': [models.UniqueConstraint(fields=('route', 'employee', 'date_start'), name='sales_unique_route_assignment'), models.UniqueConstraint(condition=models.Q(('date_end__isnull', True)), fields=('route',), name='sales_unique_active_assignment_per_route')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_status'], name='sales_sale_sale_st_8edb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='sales_sale_payment_f41ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['route'], name='sales_sale_route_i_372015_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sales_sale_custome_f0dcab_idx'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['sale'], name='sales_salel_sale_id_94a82e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['variant'], name='sales_salel_variant_0c2506_idx'),
        ),
        migrations.AddIndex(
            model_name='salelinetax',
            index=models.Index(fields=['sale_line'], name='sales_salel_sale_li_c8dc83_idx'),
        ),
        migrations.AddIndex(
            model_name='salelinetax',
            index=models.Index(fields=['tax_type'], name='sales_salel_tax_typ_79e761_idx'),
        ),
    ]
