# Generated by Django 5.2.16 on 2026-08-17 02:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customerassignment_unique_customer_assignment_and_more'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_valid_for_comission', models.BooleanField(default=True)),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='products.productclass')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='sales.route')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='sales.warehouse')),
            ],
            options={
                'verbose_name': 'Objetivo de venta',
                'verbose_name_plural': 'Objetivos de venta',
                'constraints': [models.UniqueConstraint(fields=('period', 'route', 'product_class'), name='unique_sale_target_per_period_route_class')],
            },
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(default='', max_length=255)),
                ('sale_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='products.product')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='products.productclass')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='sales.route')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='sales.warehouse')),
            ],
            options={
                'verbose_name': 'Transacción de venta',
                'verbose_name_plural': 'Transacciones de venta',
                'indexes': [models.Index(fields=['sale_date'], name='sales_salet_sale_da_35bc28_idx'), models.Index(fields=['doc_id'], name='sales_salet_doc_id_3b7d79_idx'), models.Index(fields=['route', 'sale_date'], name='sales_salet_route_i_bcd75b_idx'), models.Index(fields=['customer', 'sale_date'], name='sales_salet_custome_815706_idx')],
            },
        ),
    ]
