# Generated by Django 6.0.5 on 2026-07-29 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_contacts_customer_delivery_addresses_and_more'),
        ('human_resources', '0007_employee_unique_active_user_position_pair'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteWarehouseLogistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, help_text='Orden en el que se intenta surtir (1=Principal)')),
            ],
            options={
                'verbose_name': 'Logística de almacén en ruta',
                'verbose_name_plural': 'Logísticas de almacén en rutas',
            },
        ),
        migrations.CreateModel(
            name='UserRouteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, help_text='Indica si el usuario puede ver la ruta y su información relacionada')),
                ('can_sell', models.BooleanField(default=False, help_text='Indica si el usuario puede vender en la ruta')),
            ],
            options={
                'verbose_name': 'Acceso de usuario a ruta',
                'verbose_name_plural': 'Accesos de usuarios a rutas',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En tránsito'), ('partially_delivered', 'Entregada parcialmente'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado de la entrega de la venta', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_status',
            field=models.CharField(choices=[('not_invoiced', 'No facturada'), ('generated', 'Facturada'), ('cancelled', 'Factura cancelada')], default='not_invoiced', help_text='Estado de la factura de la venta', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Vendedor asociado a la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_sales', to='human_resources.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partially_paid', 'Pagada parcialmente'), ('paid', 'Pagada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada'), ('partially_refunded', 'Reembolsada parcialmente')], default='pending', help_text='Estado del pago de la venta', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_status',
            field=models.CharField(choices=[('quoted', 'Cotizada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='quoted', help_text='Estado de la venta', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['delivery_status'], name='sales_sale_deliver_ea753d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['invoice_status'], name='sales_sale_invoice_58a92c_idx'),
        ),
        migrations.AddField(
            model_name='routewarehouselogistic',
            name='route',
            field=models.ForeignKey(help_text='Ruta a la que se le asignará un centro de distribución', on_delete=django.db.models.deletion.CASCADE, to='sales.route'),
        ),
        migrations.AddField(
            model_name='routewarehouselogistic',
            name='warehouse',
            field=models.ForeignKey(help_text='Centro de distribución a asignar', on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='userrouteaccess',
            name='route',
            field=models.ForeignKey(help_text='Ruta a la que el usuario tiene acceso', on_delete=django.db.models.deletion.CASCADE, to='sales.route'),
        ),
        migrations.AddField(
            model_name='userrouteaccess',
            name='user',
            field=models.ForeignKey(help_text='Usuario que tiene acceso a la ruta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='routewarehouselogistic',
            constraint=models.UniqueConstraint(fields=('route', 'warehouse'), name='sales_unique_route_warehouse_logistic'),
        ),
        migrations.AddConstraint(
            model_name='routewarehouselogistic',
            constraint=models.UniqueConstraint(fields=('route', 'priority'), name='sales_unique_route_priority_logistic'),
        ),
        migrations.AddConstraint(
            model_name='userrouteaccess',
            constraint=models.UniqueConstraint(fields=('user', 'route'), name='sales_unique_user_route_access'),
        ),
    ]
