# Generated by Django 6.0.5 on 2026-07-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_businessunit_employee_business_unit'),
        ('sales', '0002_routewarehouselogistic_userrouteaccess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='route',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece la ruta. No necesariamente asociada a la unidad de negocio del colaborador que opera la ruta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_routes', to='human_resources.businessunit'),
        ),
    ]
