# Generated by Django 5.2.16 on 2026-08-17 21:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_monitoringformschedule_week_of_month'),
        ('products', '0003_alter_product_barcode_alter_product_name_and_more'),
        ('sales', '0002_saletarget_saletransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletarget',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='saletarget',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de negocio del objetivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='human_resources.businessunit'),
        ),
        migrations.AlterField(
            model_name='saletarget',
            name='is_valid_for_comission',
            field=models.BooleanField(default=True, help_text='Indica si el objetivo es válido para comisiones'),
        ),
        migrations.AlterField(
            model_name='saletarget',
            name='product_class',
            field=models.ForeignKey(help_text='Clase de producto del objetivo', on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='products.productclass'),
        ),
        migrations.AlterField(
            model_name='saletarget',
            name='route',
            field=models.ForeignKey(help_text='Ruta del objetivo', on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='sales.route'),
        ),
        migrations.AlterField(
            model_name='saletarget',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto objetivo', max_digits=18),
        ),
    ]
