# Generated by Django 6.0.5 on 2026-07-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_properties_and_more'),
        ('sales', '0003_remove_route_warehouse_route_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routewarehouselogistic',
            name='route',
            field=models.ForeignKey(help_text='Ruta a la que se le asignará un centro de distribución', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_route_warehouse_logistics', to='sales.route'),
        ),
        migrations.AlterField(
            model_name='routewarehouselogistic',
            name='warehouse',
            field=models.ForeignKey(help_text='Centro de distribución a asignar', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_route_warehouse_logistics', to='inventory.warehouse'),
        ),
    ]
