# Generated by Django 6.0.5 on 2026-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_routewarehouselogistic_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si la ruta es apta para asignación a un colaborador o esta operando'),
        ),
    ]
