# Generated by Django 6.0.5 on 2026-07-24 06:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(help_text='Identificador unico del cliente', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del cliente (nombre comercial o encargado de la cuenta)', max_length=255)),
                ('registration_date', models.DateField(help_text='Fecha de registro del cliente')),
                ('credit_limit', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Linea de credito del cliente', max_digits=18)),
                ('credit_days', models.IntegerField(default=0, help_text='Dias de credito del cliente')),
                ('opinion_leader', models.BooleanField(default=False, help_text='Indica si el cliente es un lider de opinion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CustomerClassMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_percentage', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'verbose_name': 'Margen por clase de producto',
                'verbose_name_plural': 'Márgenes por clase de producto',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.CharField(help_text='Identificador unico del tipo de cliente', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tipo de cliente', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de cliente', null=True)),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'verbose_name_plural': 'Tipos de cliente',
            },
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio de la asignación')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de fin de la asignación', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la asignación', null=True)),
                ('customer', models.ForeignKey(help_text='Cliente a asignar', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_assignments', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Asignación de cliente',
                'verbose_name_plural': 'Asignaciones de clientes',
            },
        ),
    ]
