# Generated by Django 5.2.16 on 2026-08-16 22:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.CharField(help_text='Identificador unico del tipo de cliente', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tipo de cliente', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de cliente', null=True)),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'verbose_name_plural': 'Tipos de cliente',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(help_text='Identificador del cliente', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del cliente (nombre comercial o encargado de la cuenta)', max_length=255)),
                ('registration_date', models.DateField(help_text='Fecha de registro del cliente')),
                ('credit_limit', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Linea de credito del cliente', max_digits=18)),
                ('credit_days', models.IntegerField(default=0, help_text='Dias de credito del cliente')),
                ('opinion_leader', models.BooleanField(default=False, help_text='Indica si el cliente es un lider de opinion')),
                ('customer_type', models.ForeignKey(help_text='Tipo de cliente', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.customertype')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio de la asignación')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de fin de la asignación', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la asignación', null=True)),
                ('customer', models.ForeignKey(help_text='Cliente a asignar', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.customer')),
                ('route', models.ForeignKey(help_text='Ruta a la que se asigna el cliente', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='sales.route')),
            ],
            options={
                'verbose_name': 'Asignación de cliente',
                'verbose_name_plural': 'Asignaciones de clientes',
                'constraints': [models.UniqueConstraint(fields=('customer', 'route', 'start_date'), name='unique_customer_assignment'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('customer',), name='unique_active_assignment_per_customer')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['registration_date'], name='customers_c_registr_5604c6_idx'),
        ),
    ]
