# Generated by Django 5.2.16 on 2026-08-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerassignment',
            name='unique_customer_assignment',
        ),
        migrations.AddConstraint(
            model_name='customerassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='customer_assignment_end_date_gte_start_date'),
        ),
    ]
