# Generated by Django 6.0.5 on 2026-07-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerassignment',
            name='route',
            field=models.ForeignKey(help_text='Ruta a la que se asigna el cliente', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_assignments', to='sales.route'),
        ),
        migrations.AddField(
            model_name='customerclassmargin',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_class_margins', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerclassmargin',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_customer_margins', to='inventory.productclass'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(help_text='Tipo de cliente', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_customers', to='customers.customertype'),
        ),
        migrations.AddConstraint(
            model_name='customerassignment',
            constraint=models.UniqueConstraint(fields=('customer', 'route', 'start_date'), name='unique_customer_assignment'),
        ),
        migrations.AddConstraint(
            model_name='customerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('customer',), name='unique_active_assignment_per_customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customerclassmargin',
            unique_together={('customer', 'product_class')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['registration_date'], name='customers_c_registr_5604c6_idx'),
        ),
    ]
