# Generated by Django 5.2.16 on 2026-08-17 06:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customerassignment_unique_customer_assignment_and_more'),
        ('products', '0003_alter_product_barcode_alter_product_name_and_more'),
        ('sales', '0002_saletarget_saletransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('total_balance', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=18, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('doc_id', models.CharField(blank=True, default='', max_length=255)),
                ('balance_15', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=18, null=True)),
                ('balance_30', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=18, null=True)),
                ('balance_60', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=18, null=True)),
                ('past_due', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=18, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=18, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='customers.customer')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_receivables', to='sales.route')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
            },
        ),
        migrations.CreateModel(
            name='CustomerClassMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_percentage', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_margins', to='customers.customer')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_margins', to='products.productclass')),
            ],
            options={
                'verbose_name': 'Margen por clase de producto',
                'verbose_name_plural': 'Márgenes por clase de producto',
                'unique_together': {('customer', 'product_class')},
            },
        ),
    ]
