# Generated by Django 6.0.5 on 2026-07-24 06:26

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contacts',
            field=models.JSONField(blank=True, default=list, help_text='Contactos', validators=[apps.customers.models.validate_contacts]),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_addresses',
            field=models.JSONField(blank=True, default=list, help_text='Direcciones de entrega', validators=[apps.customers.models.validate_delivery_addresses]),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_entities',
            field=models.JSONField(blank=True, default=list, help_text='Información fiscal', validators=[apps.customers.models.validate_tax_entities]),
        ),
    ]
