# Generated by Django 5.2.16 on 2026-08-17 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_accountsreceivable_customerclassmargin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='customer',
            field=models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='customers.customer'),
        ),
    ]
