# Generated by Django 5.2.16 on 2026-08-17 06:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_accountsreceivable_customer'),
        ('sales', '0002_saletarget_saletransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='balance_15',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Saldo de 1 a 15 días', max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='balance_30',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Saldo de 16 a 30 días', max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='balance_60',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Saldo de 31 a 60 días', max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Saldo al corriente', max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Concepto de la factura', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='doc_id',
            field=models.CharField(blank=True, default='', help_text='Documento', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='due_date',
            field=models.DateField(help_text='Fecha de vencimiento de la factura', null=True),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='issue_date',
            field=models.DateField(help_text='Fecha de emisión de la factura', null=True),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='past_due',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Saldo mayor a 60 días', max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Ruta que emitió la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_receivables', to='sales.route'),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text='Saldo total', max_digits=18),
        ),
    ]
