# Generated by Django 5.2.16 on 2026-09-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_accountsreceivable_balance_15_and_more'),
        ('sales', '0003_remove_saletarget_warehouse_saletarget_business_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('handover', 'Traspaso / Entrega de cuenta'), ('commercial', 'Preferencia comercial / Negociación'), ('collection', 'Cobranza / Condiciones de crédito'), ('logistics', 'Recepción / Restricciones de entrega'), ('incident', 'Queja o incidencia'), ('general', 'Nota general')], default='general', help_text='Categoría de la nota', max_length=20)),
                ('content', models.TextField(help_text='Contenido de la nota')),
                ('is_pinned', models.BooleanField(default=False, help_text='Indica si la nota está fijada')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la nota')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización de la nota')),
                ('author', models.ForeignKey(blank=True, help_text='Autor de la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_customer_notes', to=settings.AUTH_USER_MODEL)),
                ('current_route', models.ForeignKey(blank=True, help_text='Ruta asignada al momento de la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_customer_notes', to='sales.route')),
                ('customer', models.ForeignKey(help_text='Cliente al que pertenece la nota', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Nota de cliente',
                'verbose_name_plural': 'Notas de clientes',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['customer', '-is_pinned', '-created_at'], name='customers_c_custome_779c36_idx'), models.Index(fields=['created_at'], name='customers_c_created_66440c_idx')],
            },
        ),
    ]
