# Generated by Django 5.2.16 on 2026-09-21 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del contacto', max_length=200)),
                ('role', models.CharField(choices=[('owner', 'Dueño / Dirección'), ('purchasing', 'Compras / Adquisiciones'), ('collection', 'Pagos / Cuentas por pagar'), ('warehouse', 'Almacén / Recepción'), ('general', 'Contacto general')], default='general', help_text='Función o área del contacto', max_length=30)),
                ('phone', models.CharField(blank=True, help_text='Teléfono de oficina o directo', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Celular / WhatsApp', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si es el contacto principal')),
                ('notes', models.CharField(blank=True, help_text='Notas breves', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Cliente al que pertenece el contacto', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Contacto de cliente',
                'verbose_name_plural': 'Contactos de clientes',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
