# Generated by Django 5.2.16 on 2026-09-23 22:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customercontact'),
        ('products', '0003_alter_product_barcode_alter_product_name_and_more'),
        ('sales', '0003_remove_saletarget_warehouse_saletarget_business_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('physical', 'Artículo'), ('fixed_discount', 'Descuento fijo'), ('percentage_discount', 'Descuento porcentual')], default='physical', help_text='Tipo de beneficio comercial', max_length=25)),
                ('name', models.CharField(help_text='Nombre descriptivo del beneficio comercial', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total del beneficio para la empresa', max_digits=14)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el beneficio está disponible')),
            ],
            options={
                'verbose_name': 'Beneficio comercial',
                'verbose_name_plural': 'Beneficios comerciales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, help_text='Folio único del convenio (autogenerado de 5 caracteres si se omite)', max_length=50, unique=True)),
                ('agreement_type', models.CharField(choices=[('st', 'Corto plazo'), ('mt', 'Medio plazo'), ('lt', 'Largo plazo')], default='st', help_text='Clasificación de plazo del convenio', max_length=5)),
                ('start_date', models.DateField(help_text='Fecha de inicio del convenio (primer día del mes)')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de fin del convenio (último día del mes)', null=True)),
                ('global_target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto objetivo global por periodo de evaluación', max_digits=18)),
                ('target_frequency', models.CharField(choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='1m', help_text='Frecuencia de evaluación y penalización de ventas vs objetivo', max_length=3)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de penalización en caso de incumplimiento del periodo', max_digits=18)),
                ('growth_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de crecimiento periódico exigido (ej. 5.00 para 5%)', max_digits=5)),
                ('growth_frequency', models.CharField(blank=True, choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='', help_text='Frecuencia en la que se incrementa la cuota de ventas', max_length=3)),
                ('related_doc', models.FileField(blank=True, help_text='Archivo escaneado o digital del convenio firmado (único campo editable en la app regular)', null=True, upload_to='customer_agreements/documents/')),
                ('margin_warning_accepted', models.BooleanField(default=False, help_text='Indica si el usuario autorizó la creación aun con alerta de margen bajo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit', models.ForeignKey(help_text='Beneficio comercial pactado', on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='customers.commercialbenefit')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que registró el convenio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Cliente al que se le otorga el convenio', on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='customers.customer')),
                ('route', models.ForeignKey(help_text='Ruta que originó el convenio', on_delete=django.db.models.deletion.PROTECT, related_name='customer_agreements', to='sales.route')),
            ],
            options={
                'verbose_name': 'Convenio comercial',
                'verbose_name_plural': 'Convenios comerciales',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementEvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(help_text='Número secuencial del periodo (1, 2, ...)')),
                ('start_date', models.DateField(help_text='Fecha inicial del periodo de evaluación')),
                ('end_date', models.DateField(help_text='Fecha final del periodo de evaluación')),
                ('expected_global_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Objetivo global esperado para este periodo (con crecimiento aplicado si aplica)', max_digits=18)),
                ('achieved_global_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ventas netas globales alcanzadas en el periodo', max_digits=18)),
                ('amortized_benefit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del beneficio amortizado en este periodo', max_digits=18)),
                ('period_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Utilidad neta del periodo considerando amortización de beneficio', max_digits=18)),
                ('period_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Margen porcentual neto del periodo', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'En progreso'), ('evaluating', 'En evaluación'), ('achieved', 'Alcanzado'), ('failed', 'No alcanzado')], default='pending', help_text='Estado de cumplimiento del periodo', max_length=20)),
                ('penalty_applied', models.BooleanField(default=False, help_text='Indica si se aplicó penalización por incumplimiento')),
                ('observations', models.TextField(blank=True, default='', help_text='Detalles u observaciones del periodo')),
                ('agreement', models.ForeignKey(help_text='Convenio asociado', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_periods', to='customers.customeragreement')),
            ],
            options={
                'verbose_name': 'Periodo de evaluación de convenio',
                'verbose_name_plural': 'Periodos de evaluación de convenios',
                'ordering': ['agreement', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='AgreementClassTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Objetivo de compra individual para esta clase de producto', max_digits=18)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Si es verdadero, el no alcanzar este objetivo individual invalida el periodo')),
                ('product_class', models.ForeignKey(help_text='Clase de producto participante', on_delete=django.db.models.deletion.PROTECT, related_name='agreement_targets', to='products.productclass')),
                ('agreement', models.ForeignKey(help_text='Convenio al que aplica el objetivo por clase', on_delete=django.db.models.deletion.CASCADE, related_name='class_targets', to='customers.customeragreement')),
            ],
            options={
                'verbose_name': 'Objetivo por clase de producto',
                'verbose_name_plural': 'Objetivos por clase de producto',
            },
        ),
        migrations.CreateModel(
            name='AgreementPeriodClassResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_class_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Objetivo individual esperado para esta clase en el periodo', max_digits=18)),
                ('achieved_class_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Venta neta real alcanzada en esta clase en el periodo', max_digits=18)),
                ('evaluation_period', models.ForeignKey(help_text='Periodo de evaluación', on_delete=django.db.models.deletion.CASCADE, related_name='class_results', to='customers.agreementevaluationperiod')),
                ('product_class', models.ForeignKey(help_text='Clase de producto evaluada', on_delete=django.db.models.deletion.PROTECT, related_name='period_class_results', to='products.productclass')),
            ],
            options={
                'verbose_name': 'Resultado de clase por periodo',
                'verbose_name_plural': 'Resultados de clase por periodo',
                'unique_together': {('evaluation_period', 'product_class')},
            },
        ),
        migrations.AddIndex(
            model_name='customeragreement',
            index=models.Index(fields=['customer', 'start_date', 'end_date'], name='customers_c_custome_f299d7_idx'),
        ),
        migrations.AddIndex(
            model_name='customeragreement',
            index=models.Index(fields=['doc_id'], name='customers_c_doc_id_8e19b1_idx'),
        ),
        migrations.AddIndex(
            model_name='customeragreement',
            index=models.Index(fields=['route', 'start_date'], name='customers_c_route_i_8b7bfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeragreement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='customer_agreement_end_date_gte_start_date'),
        ),
        migrations.AlterUniqueTogether(
            name='agreementevaluationperiod',
            unique_together={('agreement', 'period_number')},
        ),
        migrations.AlterUniqueTogether(
            name='agreementclasstarget',
            unique_together={('agreement', 'product_class')},
        ),
    ]
