# Generated by Django 5.2.16 on 2026-09-24

from django.db import migrations, models


def create_default_agreement_edit_reference(apps, schema_editor):
    Reference = apps.get_model('core', 'Reference')
    Reference.objects.get_or_create(
        key='can_edit_customer_agreement',
        value='gerente_cedis',
        defaults={
            'context': 'permiso_edicion_convenio',
        }
    )


def remove_default_agreement_edit_reference(apps, schema_editor):
    Reference = apps.get_model('core', 'Reference')
    Reference.objects.filter(
        key='can_edit_customer_agreement',
        value='gerente_cedis'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reference'),
        ('customers', '0008_commercialbenefit_customeragreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='benefit_already_provided',
            field=models.BooleanField(
                default=False,
                help_text='Indica si el beneficio comercial ya fue entregado al cliente',
                verbose_name='Beneficio entregado'
            ),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='signed',
            field=models.BooleanField(
                default=False,
                help_text='Indica si el cliente ya firmó el documento o contrato del convenio',
                verbose_name='Firmado'
            ),
        ),
        migrations.AlterField(
            model_name='customeragreement',
            name='related_doc',
            field=models.FileField(
                blank=True,
                help_text='Archivo escaneado o digital del convenio firmado',
                null=True,
                upload_to='customer_agreements/documents/'
            ),
        ),
        migrations.RunPython(
            create_default_agreement_edit_reference,
            remove_default_agreement_edit_reference
        ),
    ]
