# Generated by Django 5.2.16 on 2026-09-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customeragreement_evaluation_mode_and_more'),
        ('sales', '0003_remove_saletarget_warehouse_saletarget_business_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(
                    blank=True,
                    choices=[
                        ('2w', '2 Semanas'),
                        ('1m', '1 Mes'),
                        ('2m', '2 Meses'),
                        ('3m', '3 Meses'),
                        ('4m', '4 Meses'),
                        ('6m', '6 Meses'),
                        ('1y', '1 Año'),
                    ],
                    help_text='Periodicidad de la visita comercial según PeriodicityChoices (ej. 2w, 1m). Si se deja en blanco, la visita es semanal en los días asignados.',
                    max_length=5,
                    null=True
                )),
                ('visit_monday', models.BooleanField(default=False, verbose_name='Lunes')),
                ('visit_tuesday', models.BooleanField(default=False, verbose_name='Martes')),
                ('visit_wednesday', models.BooleanField(default=False, verbose_name='Miércoles')),
                ('visit_thursday', models.BooleanField(default=False, verbose_name='Jueves')),
                ('visit_friday', models.BooleanField(default=False, verbose_name='Viernes')),
                ('visit_saturday', models.BooleanField(default=False, verbose_name='Sábado')),
                ('visit_sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('start_date', models.DateField(help_text='Fecha de inicio de vigencia de este esquema de visitas')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de término de vigencia de este esquema de visitas', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Observaciones o especificaciones sobre las visitas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    help_text='Usuario que registró o modificó este esquema de visitas',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_visit_schedules',
                    to=settings.AUTH_USER_MODEL
                )),
                ('customer', models.ForeignKey(
                    help_text='Cliente al que pertenece el esquema de visitas',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='visit_schedules',
                    to='customers.customer'
                )),
                ('route', models.ForeignKey(
                    blank=True,
                    help_text='Ruta activa asignada al cliente al momento de la configuración',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='customer_visit_schedules',
                    to='sales.route'
                )),
            ],
            options={
                'verbose_name': 'Esquema de visitas de cliente',
                'verbose_name_plural': 'Esquemas de visitas de clientes',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['customer', 'start_date', 'end_date'], name='customers_c_custome_338a0a_idx'),
                    models.Index(fields=['start_date'], name='customers_c_start_d_b06fc8_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(end_date__isnull=True),
                        fields=['customer'],
                        name='unique_active_visit_schedule_per_customer'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(end_date__isnull=True) | models.Q(end_date__gte=models.F('start_date')),
                        name='customer_visit_schedule_end_date_gte_start_date'
                    ),
                ],
            },
        ),
    ]
