services:
  redis:
    image: redis:7-alpine
    container_name: datall_bi_redis
    restart: always
    ports:
      - "6380:6379"

  web:
    build: .
    container_name: datall_bi_web
    restart: always
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8090:8000"
    depends_on:
      - redis

  qcluster:
    build: .
    container_name: datall_bi_qcluster
    restart: always
    env_file:
      - .env
    command: python manage.py qcluster
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - web
      - redis
