services:
  db:
    image: postgres:16-alpine
    container_name: datall_bi_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - datall_bi_postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: datall_bi_web
    restart: always
    env_file:
      - .env
    ports:
      - "8090:8000"
    depends_on:
      - db

volumes:
  datall_bi_postgres_data:
