# Generated by Django 6.0.5 on 2026-06-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Route type',
                'verbose_name_plural': 'Route types',
                'db_table': 'route_types',
            },
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Sale channel',
                'verbose_name_plural': 'Sale channels',
                'db_table': 'sale_channels',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_type', models.CharField(blank=True, choices=[('v', 'Porcentaje'), ('f', 'Monto Fijo'), ('na', 'Sin comisión')], default='na', max_length=5, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.warehouse')),
                ('route_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.routetype')),
                ('sale_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.salechannel')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='core.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.route')),
            ],
            options={
                'verbose_name': 'Route assignment',
                'verbose_name_plural': 'Route assignments',
                'db_table': 'route_assignments',
                'constraints': [models.UniqueConstraint(fields=('route', 'employee', 'start_date'), name='unique_route_assignment'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('route',), name='unique_active_assignment_per_route')],
            },
        ),
    ]
