# Generated by Django 5.2.16 on 2026-08-03 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_user_options_remove_user_tax_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', help_text='Nombre del icono', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del submódulo visible al usuario', max_length=100)),
                ('url_name', models.CharField(help_text='Url asociada al submódulo, de formato app_label:url_name', max_length=150)),
                ('icon', models.CharField(blank=True, default='', help_text='Nombre del icono', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del submódulo en el menú')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el submódulo está activo y se muestra al usuario')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Grupos autorizados para acceder al submódulo', related_name='accessible_submodules', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Usuarios autorizados para acceder al submódulo', related_name='accessible_submodules', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Módulo al que pertenece el submódulo', on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.module')),
            ],
            options={
                'verbose_name': 'Submódulo',
                'verbose_name_plural': 'Submódulos',
                'ordering': ['order'],
            },
        ),
    ]
