# Generated by Django 6.0.5 on 2026-06-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_routetype_salechannel_route_routeassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='route',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='notes',
        ),
        migrations.AddField(
            model_name='position',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.position'),
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_regions', to='core.employee')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='core.region'),
        ),
    ]
