# Generated by Django 6.0.5 on 2026-06-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_route_commission_remove_route_commission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
