# Generated by Django 5.2.16 on 2026-08-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_submodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='submodule',
            name='icon',
        ),
    ]
