# Generated by Django 5.2.16 on 2026-08-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_remove_module_icon_remove_submodule_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, default='', help_text='Descripción o valor que indica el contexto de uso (formato notacion_guion_bajo). Ej: mapeo_columnas_archivo_ventas', max_length=100)),
                ('key', models.CharField(blank=True, default='', help_text='Valor crudo usado para ser mapeado', max_length=100)),
                ('value', models.CharField(blank=True, default='', help_text='Valor homologado resultante del mapeo', max_length=100)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tabla o modelo al cual se le aplica el valor homologado de la referencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='contenttypes.contenttype')),
                ('submodule', models.ForeignKey(blank=True, help_text='Módulo en el cual dicha referencia va a ser usada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.submodule')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
    ]
