# Generated by Django 6.0.5 on 2026-06-08 04:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_region_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer type',
                'verbose_name_plural': 'Customer types',
                'db_table': 'customer_types',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_days', models.IntegerField(default=0)),
                ('opinion_leader', models.BooleanField(default=False)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='core.route')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='core.customertype')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='SaleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_valid_for_comission', models.BooleanField(default=True)),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='core.productclass')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='core.route')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_targets', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Sale target',
                'verbose_name_plural': 'Sale targets',
                'db_table': 'sale_targets',
            },
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=255)),
                ('sale_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('profit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='core.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='core.product')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='core.productclass')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='core.route')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Sale transaction',
                'verbose_name_plural': 'Sale transactions',
                'db_table': 'sale_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['registration_date'], name='customers_registr_3b03b8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['route', 'customer_type'], name='customers_route_i_b3555c_idx'),
        ),
        migrations.AddConstraint(
            model_name='saletarget',
            constraint=models.UniqueConstraint(fields=('period', 'route', 'product_class'), name='unique_sale_target_per_period_route_class'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['sale_date'], name='sale_transa_sale_da_3fafd1_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['doc_id'], name='sale_transa_doc_id_f3a1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['route', 'sale_date'], name='sale_transa_route_i_766f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['customer', 'sale_date'], name='sale_transa_custome_f5c6b2_idx'),
        ),
    ]
