# Generated by Django 5.2.16 on 2026-08-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='icon',
            field=models.TextField(blank=True, default='', help_text='Código SVG del ícono del submódulo'),
        ),
    ]
