# Generated by Django 6.0.5 on 2026-06-09 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_customertype_customer_saletarget_saletransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, help_text='ID del registro afectado en esa tabla.', max_length=255, null=True)),
                ('action', models.CharField(choices=[('importación', 'importación'), ('exportación', 'exportación'), ('creación', 'creación'), ('actualización', 'actualización'), ('eliminación', 'eliminación'), ('lectura', 'lectura'), ('inicio de sesión', 'inicio de sesión'), ('cierre de sesión', 'cierre de sesión')], max_length=50)),
                ('result', models.CharField(choices=[('éxito', 'éxito'), ('parcial', 'parcial'), ('error', 'error')], default='éxito', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Descripción legible para humanos.', null=True)),
                ('changes', models.JSONField(blank=True, help_text='Payload JSON con el estado anterior y nuevo, o detalles del error.', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tabla/Modelo afectado, e.g. auth_user, sales_route.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_history', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='Módulo del sistema donde se originó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_logs', to='core.systemmodule')),
            ],
            options={
                'verbose_name': 'Data History',
                'verbose_name_plural': 'Data Histories',
                'db_table': 'data_history',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='data_histor_content_0e500a_idx')],
            },
        ),
    ]
