# Generated by Django 5.2.16 on 2026-08-23 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submodule_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del reporte', max_length=255)),
                ('module_name', models.CharField(default='analytics', help_text='Módulo de origen', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En proceso'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-created_at'],
            },
        ),
    ]
