# Generated by Django 6.0.5 on 2026-06-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_datahistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True)),
                ('balance_15', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True)),
                ('balance_30', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True)),
                ('balance_60', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True)),
                ('past_due', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True)),
                ('period', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='core.customer')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_receivables', to='core.route')),
            ],
            options={
                'verbose_name': 'Accounts receivable',
                'verbose_name_plural': 'Accounts receivables',
                'db_table': 'accounts_receivables',
            },
        ),
    ]
