# Generated by Django 5.2.16 on 2026-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya vio el reporte completado'),
        ),
    ]
