# Generated by Django 6.0.5 on 2026-06-10 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_accountsreceivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tabla/Modelo afectado, e.g. auth_user, sales_route.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
