# Generated by Django 6.0.5 on 2026-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_alter_product_cost_alter_product_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reference',
            name='unique_module_context_key_mapping',
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('module', 'field_context', 'key', 'content_type'), name='unique_module_context_key_mapping'),
        ),
    ]
