# Generated by Django 5.2.16 on 2026-09-02 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de categoría', max_length=100)),
                ('description', models.CharField(blank=True, default='', help_text='Descripción corta', max_length=255)),
                ('icon', models.CharField(default='help-circle', help_text='Nombre del ícono Lucide (ej: help-circle, key, shield, file-text, phone, sliders, database, user)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Soporte',
                'verbose_name_plural': 'Categorías de Soporte',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título o Pregunta', max_length=200)),
                ('content', models.TextField(help_text='Describe la solución o guía. Puedes usar formato Markdown.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden')),
                ('is_published', models.BooleanField(default=True, help_text='Publicado')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Si se marca, se muestra en la sección de preguntas destacadas/frecuentes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoría', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.supportcategory')),
            ],
            options={
                'verbose_name': 'Artículo / Pregunta',
                'verbose_name_plural': 'Artículos y Preguntas',
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
