# Generated by Django 5.2.16 on 2026-09-02 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_supportcategory_supportarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Ruta URL solicitada (ej: /analytics/target-achievement/)', max_length=500)),
                ('view_name', models.CharField(blank=True, default='', help_text='Nombre de la ruta/vista Django (ej: analytics:target_achievement_view)', max_length=200)),
                ('http_method', models.CharField(default='GET', help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('action', models.CharField(choices=[('view', 'Visualización'), ('filter', 'Filtrado / Búsqueda'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('export', 'Exportación'), ('import', 'Importación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], default='view', max_length=50)),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error')], default='success', max_length=20)),
                ('status_code', models.IntegerField(blank=True, help_text='Código de respuesta HTTP (ej: 200, 302, 500)', null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Filtros GET o parámetros de búsqueda aplicados')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Valores anteriores vs nuevos o detalles del error')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Navegador o dispositivo')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.submodule')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx'), models.Index(fields=['view_name', '-created_at'], name='core_activi_view_na_d94a3d_idx'), models.Index(fields=['action', '-created_at'], name='core_activi_action_a01617_idx'), models.Index(fields=['content_type', 'object_id'], name='core_activi_content_1a7154_idx')],
            },
        ),
    ]
