# Generated by Django 6.0.5 on 2026-06-17 20:35

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_reference_unique_module_context_key_mapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefit_type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio'), ('discount', 'Descuento'), ('other', 'Otro')], default='product', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/benefits')),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'db_table': 'benefits',
            },
        ),
        migrations.AlterField(
            model_name='datahistory',
            name='changes',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Payload JSON con el estado anterior y nuevo, o detalles del error.', null=True),
        ),
        migrations.CreateModel(
            name='CustomerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('lt', 'largo plazo'), ('mt', 'medio plazo'), ('st', 'corto plazo')], default='st', max_length=2)),
                ('doc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_granted', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('agreed_benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_agreements', to='core.benefit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='core.customer')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_agreements', to='core.route')),
                ('target_freq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_agreements', to='core.periodicity')),
            ],
        ),
    ]
