# Generated by Django 6.0.5 on 2026-06-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_reference_unique_module_context_key_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahistory',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Filtros de búsqueda, parámetros de URL o metadatos extra.', null=True),
        ),
    ]
