# Generated by Django 6.0.5 on 2026-06-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_benefit_alter_datahistory_changes_customeragreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeragreement',
            options={'verbose_name': 'Customer agreement', 'verbose_name_plural': 'Customer agreements'},
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='growth_freq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_agreements', to='core.periodicity'),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='growth_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='penalty_freq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_agreements', to='core.periodicity'),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='related_doc',
            field=models.FileField(blank=True, null=True, upload_to='agreements'),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='periodicity',
            name='months_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(choices=[('product', 'producto'), ('service', 'servicio'), ('discount', 'descuento'), ('other', 'otro')], default='product', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customeragreement',
            table='customer_agreements',
        ),
        migrations.CreateModel(
            name='AgreementEvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_global_target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('achieved_global_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'pendiente'), ('evaluando', 'en evaluación'), ('alcanzado', 'objetivo cumplido'), ('no_alcanzado', 'objetivo no cumplido')], default='pendiente', max_length=20)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, max_length=500, null=True)),
                ('customer_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_periods', to='core.customeragreement')),
            ],
            options={
                'verbose_name': 'Agreement evaluation period',
                'verbose_name_plural': 'Agreement evaluation periods',
                'db_table': 'agreement_evaluation_periods',
            },
        ),
        migrations.CreateModel(
            name='AgreementPeriodLineTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_line_target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('achieved_line_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_lines', to='core.agreementevaluationperiod')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_period_lines', to='core.productclass')),
            ],
            options={
                'verbose_name': 'Agreement period line target',
                'verbose_name_plural': 'Agreement period lines target',
                'db_table': 'agreement_period_lines_target',
            },
        ),
        migrations.CreateModel(
            name='AgreementProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('customer_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='core.customeragreement')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_agreement_product_lines', to='core.productclass')),
            ],
            options={
                'verbose_name': 'Customer agreement product line',
                'verbose_name_plural': 'Customer agreement product lines',
                'db_table': 'customer_agreement_product_lines',
            },
        ),
    ]
