# Generated by Django 6.0.5 on 2026-06-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_datahistory_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Commission profile',
                'verbose_name_plural': 'Commission profiles',
                'db_table': 'commission_profiles',
            },
        ),
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'borrador'), ('closed', 'cerrado')], default='draft', max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_profile_name', models.CharField(max_length=100)),
                ('snapshot_net_sales', models.DecimalField(decimal_places=2, max_digits=18)),
                ('snapshot_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('snapshot_global_scope', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snapshot_completed_classes', models.IntegerField()),
                ('snapshot_base_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_calculated_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_global_scope_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_completed_classes', models.IntegerField(default=0)),
                ('bonus_multiplier_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_flat_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_tiers', to='core.commissionprofile')),
            ],
            options={
                'verbose_name': 'Commission tier',
                'verbose_name_plural': 'Commission tiers',
                'db_table': 'commission_tiers',
                'ordering': ['-min_global_scope_pct', '-min_completed_classes'],
            },
        ),
        migrations.CreateModel(
            name='RouteCommissionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope_tolerance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('guaranteed_flat_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_exceptions', to='core.route')),
            ],
            options={
                'verbose_name': 'Route commission exception',
                'verbose_name_plural': 'Route commission exceptions',
                'db_table': 'route_commission_exception',
            },
        ),
        migrations.CreateModel(
            name='RouteCommissionSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bonus_type', models.CharField(choices=[('f', 'fijo'), ('v', 'variable')], default='v', max_length=10)),
                ('base_bonus_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.commissionprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_history', to='core.route')),
            ],
            options={
                'verbose_name': 'Route commission setup',
                'verbose_name_plural': 'Route commission setups',
                'db_table': 'route_commission_setup',
            },
        ),
    ]
