# Generated by Django 6.0.5 on 2026-06-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_commissionprofile_commissionsettlement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionsettlement',
            options={'ordering': ['-period_start'], 'verbose_name': 'Commission settlement', 'verbose_name_plural': 'Commission settlements'},
        ),
        migrations.AlterModelTable(
            name='commissionsettlement',
            table='commission_settlement',
        ),
    ]
