# Generated by Django 6.0.5 on 2026-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_commissionsettlement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='period',
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
