# Generated by Django 6.0.5 on 2026-07-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='novelties')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Novelty',
                'verbose_name_plural': 'Novelties',
                'db_table': 'novelties',
                'indexes': [models.Index(fields=['created_at'], name='novelties_created_e52039_idx')],
            },
        ),
    ]
