# Generated by Django 6.0.5 on 2026-07-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_novelty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelty',
            name='content',
            field=models.TextField(),
        ),
    ]
