# Generated by Django 6.0.5 on 2026-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_novelty_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelty',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='novelties'),
        ),
    ]
