# Generated by Django 6.0.5 on 2026-07-11 02:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_novelty_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementEvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_global_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('achieved_global_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amortized_benefit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('period_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('period_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('evaluating', 'evaluando'), ('achieved', 'alcanzado'), ('not_achieved', 'no alcanzado')], default='pending', max_length=20)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agreement evaluation period',
                'verbose_name_plural': 'Agreement evaluation periods',
                'db_table': 'agreement_evaluation_periods',
            },
        ),
        migrations.CreateModel(
            name='AgreementPeriodClassResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_class_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('achieved_class_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_results', to='core.agreementevaluationperiod')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_results', to='core.productclass')),
            ],
            options={
                'db_table': 'agreement_period_class_results',
            },
        ),
        migrations.CreateModel(
            name='CommercialBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Hielera, Descuento 5%, Bono $1000', max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('benefit_type', models.CharField(choices=[('physical', 'artículo'), ('fixed_desc', 'descuento fijo'), ('pct_desc', 'descuento porcentual')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='benefits')),
                ('stock', models.IntegerField(default=0, help_text='Solo aplica para artículos físicos')),
                ('discount_value', models.DecimalField(decimal_places=6, default=0, help_text='Monto fijo o porcentaje (%). Solo aplica si es descuento.', max_digits=18)),
                ('cost', models.DecimalField(decimal_places=6, default=0, help_text='Costo del artículo o impacto total para la empresa', max_digits=18)),
                ('amortization_periods', models.IntegerField(default=1, help_text='En cuántos periodos se divide este costo para el cálculo de utilidad real')),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(blank=True, help_text='Requerido si es un artículo físico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_benefits', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Commercial benefit',
                'verbose_name_plural': 'Commercial benefits',
                'db_table': 'commercial_benefits',
            },
        ),
        migrations.CreateModel(
            name='CustomerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement_name', models.CharField(max_length=255)),
                ('agreement_type', models.CharField(choices=[('lt', 'largo plazo'), ('mt', 'medio plazo'), ('st', 'corto plazo')], default='st', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('global_target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('growth_value', models.DecimalField(decimal_places=2, default=0, help_text='Puede ser % o monto fijo', max_digits=18)),
                ('related_doc', models.FileField(blank=True, null=True, upload_to='customer_agreements')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='core.commercialbenefit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='core.customer')),
                ('growth_freq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_agreements', to='core.periodicity')),
                ('penalty_freq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_agreements', to='core.periodicity')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_agreements', to='core.route')),
                ('target_freq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_agreements', to='core.periodicity')),
            ],
            options={
                'verbose_name': 'Customer agreement',
                'verbose_name_plural': 'Customer agreements',
                'db_table': 'customer_agreements',
            },
        ),
        migrations.AddField(
            model_name='agreementevaluationperiod',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_periods', to='core.customeragreement'),
        ),
        migrations.CreateModel(
            name='AgreementClassTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Si es falso, suma al global pero no es restrictivo.')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_targets', to='core.productclass')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_targets', to='core.customeragreement')),
            ],
            options={
                'verbose_name': 'Agreement class target',
                'verbose_name_plural': 'Agreement class targets',
                'db_table': 'agreement_class_targets',
                'unique_together': {('agreement', 'product_class')},
            },
        ),
        migrations.CreateModel(
            name='CustomerClassMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_margins', to='core.customer')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_margins', to='core.productclass')),
            ],
            options={
                'verbose_name': 'Customer class margin',
                'verbose_name_plural': 'Customer class margins',
                'db_table': 'customer_class_margins',
                'unique_together': {('customer', 'product_class')},
            },
        ),
    ]
