# Generated by Django 6.0.5 on 2026-07-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_agreementevaluationperiod_agreementperiodclassresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialbenefit',
            name='amortization_periods',
        ),
    ]
