# Generated by Django 6.0.5 on 2026-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_commercialbenefit_amortization_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbenefit',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='benefits'),
        ),
    ]
