# Generated by Django 6.0.5 on 2026-07-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_commercialbenefit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Example: 1.0.0, 2.1.4-beta', max_length=50, unique=True, verbose_name='Version number')),
                ('release_type', models.CharField(choices=[('MAJOR', 'Mayor'), ('MINOR', 'Menor'), ('PATCH', 'Parche')], default='PATCH', max_length=10, verbose_name='Release type')),
                ('release_date', models.DateField(help_text='Release date', verbose_name='Release date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Example: Security update or UI redesign', max_length=200, verbose_name='Short Title')),
                ('description', models.TextField(help_text='Describe the changes detailed. You can use Markdown format.', verbose_name='Details')),
                ('is_published', models.BooleanField(default=False, help_text='If checked, it will be displayed in the public documentation.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-release_date', '-id'],
            },
        ),
    ]
