# Generated by Django 6.0.5 on 2026-07-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsreceivable',
            options={'verbose_name': 'Cuentas por cobrar', 'verbose_name_plural': 'Cuentas por cobrar'},
        ),
        migrations.AlterModelOptions(
            name='agreementclasstarget',
            options={'verbose_name': 'Objetivo de convenio por clase de producto', 'verbose_name_plural': 'Objetivos de convenio por clase de producto'},
        ),
        migrations.AlterModelOptions(
            name='agreementevaluationperiod',
            options={'verbose_name': 'Periodo de evaluación de convenio', 'verbose_name_plural': 'Periodos de evaluación de convenios'},
        ),
        migrations.AlterModelOptions(
            name='agreementperiodclassresult',
            options={'verbose_name': 'Resultado de periodo por clase de producto', 'verbose_name_plural': 'Resultados de periodos por clase de producto'},
        ),
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-release_date', '-id'], 'verbose_name': 'Versión de la aplicación', 'verbose_name_plural': 'Versiones de la aplicación'},
        ),
        migrations.AlterModelOptions(
            name='commercialbenefit',
            options={'verbose_name': 'Beneficio comercial', 'verbose_name_plural': 'Beneficios comerciales'},
        ),
        migrations.AlterModelOptions(
            name='commissionprofile',
            options={'verbose_name': 'Perfil de comisión', 'verbose_name_plural': 'Perfiles de comisión'},
        ),
        migrations.AlterModelOptions(
            name='commissionsettlement',
            options={'ordering': ['-period_start'], 'verbose_name': 'Liquidación de comisión', 'verbose_name_plural': 'Liquidaciones de comisión'},
        ),
        migrations.AlterModelOptions(
            name='commissiontier',
            options={'ordering': ['-min_global_scope_pct', '-min_completed_classes'], 'verbose_name': 'Umbral de comision', 'verbose_name_plural': 'Umbrales de comision'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='customeragreement',
            options={'verbose_name': 'Convenio', 'verbose_name_plural': 'Convenios'},
        ),
        migrations.AlterModelOptions(
            name='customerclassmargin',
            options={'verbose_name': 'Márgen de clase de producto', 'verbose_name_plural': 'Márgenes de clase de producto'},
        ),
        migrations.AlterModelOptions(
            name='customertype',
            options={'verbose_name': 'Tipo de cliente', 'verbose_name_plural': 'Tipos de clientes'},
        ),
        migrations.AlterModelOptions(
            name='datahistory',
            options={'verbose_name': 'Historial de datos', 'verbose_name_plural': 'Historiales de datos'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ['order'], 'verbose_name': 'Sección de menú', 'verbose_name_plural': 'Secciones de menú'},
        ),
        migrations.AlterModelOptions(
            name='novelty',
            options={'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.AlterModelOptions(
            name='payrolltype',
            options={'verbose_name': 'Tipo de compensación', 'verbose_name_plural': 'Tipos de compensaciones'},
        ),
        migrations.AlterModelOptions(
            name='periodicity',
            options={'ordering': ['id'], 'verbose_name': 'Periodicidad', 'verbose_name_plural': 'Periodicidades'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de producto'},
        ),
        migrations.AlterModelOptions(
            name='productclass',
            options={'verbose_name': 'Clase de producto', 'verbose_name_plural': 'Clases de producto'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='routeassignment',
            options={'verbose_name': 'Asignación de ruta', 'verbose_name_plural': 'Asignaciones de rutas'},
        ),
        migrations.AlterModelOptions(
            name='routecommissionexception',
            options={'verbose_name': 'Excepción de comisión de ruta', 'verbose_name_plural': 'Excepciones de comisión de ruta'},
        ),
        migrations.AlterModelOptions(
            name='routecommissionsetup',
            options={'verbose_name': 'Configuración de comisión de ruta', 'verbose_name_plural': 'Configuraciones de comisión de ruta'},
        ),
        migrations.AlterModelOptions(
            name='routetype',
            options={'verbose_name': 'Tipo de ruta', 'verbose_name_plural': 'Tipos de ruta'},
        ),
        migrations.AlterModelOptions(
            name='salechannel',
            options={'verbose_name': 'Canal de venta', 'verbose_name_plural': 'Canales de venta'},
        ),
        migrations.AlterModelOptions(
            name='saletarget',
            options={'verbose_name': 'Objetivo de venta', 'verbose_name_plural': 'Objetivos de venta'},
        ),
        migrations.AlterModelOptions(
            name='saletransaction',
            options={'verbose_name': 'Transacción de venta', 'verbose_name_plural': 'Transacciones de venta'},
        ),
        migrations.AlterModelOptions(
            name='systemmodule',
            options={'ordering': ['section__order', 'order'], 'verbose_name': 'Módulo del sistema', 'verbose_name_plural': 'Módulos del sistema'},
        ),
        migrations.AlterModelOptions(
            name='taxsystem',
            options={'verbose_name': 'Régimen fiscal', 'verbose_name_plural': 'Regímenes fiscales'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Gerencia', 'verbose_name_plural': 'Gerencias'},
        ),
    ]
