# Generated by Django 6.0.5 on 2026-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='in_transit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
