# Generated by Django 6.0.5 on 2026-07-21 23:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la cuenta según el plan contable, ej: 110501', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre de la cuenta, ej: Caja General', max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Capital'), ('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], help_text='Tipo de cuenta', max_length=20)),
                ('balance', models.DecimalField(decimal_places=6, default=0.0, help_text='Saldo actual de la cuenta', max_digits=18)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha de la transacción')),
                ('reference', models.CharField(help_text='Referencia de la transacción', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Descripción de la transacción', max_length=200)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'db_table': 'journal_entries',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
        ),
    ]
