# Generated by Django 6.0.5 on 2026-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Nivel de la cuenta (1=Mayor/Encabezado, 2=Subcuenta, etc.)'),
        ),
    ]
