# Generated by Django 6.0.5 on 2026-07-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre (nivel superior)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='accounting.account'),
        ),
    ]
