# Generated by Django 6.0.5 on 2026-07-23 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Número de versión, ej. 1.0.0, 2.1.4-beta', max_length=50, unique=True)),
                ('release_type', models.CharField(choices=[('MAJOR', 'Mayor'), ('MINOR', 'Menor'), ('PATCH', 'Parche')], default='PATCH', help_text='Tipo de lanzamiento', max_length=10)),
                ('release_date', models.DateField(help_text='Fecha de lanzamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de actualización')),
                ('title', models.CharField(blank=True, help_text='Título corto, ej. Actualización de seguridad o Rediseño de UI', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada de los cambios.')),
                ('is_published', models.BooleanField(default=False, help_text='Si está marcado, se mostrará en la documentación pública.')),
            ],
            options={
                'verbose_name': 'Versión de la aplicación',
                'verbose_name_plural': 'Versiones de la aplicación',
                'ordering': ['-release_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la sección de menú', max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú')),
            ],
            options={
                'verbose_name': 'Sección de menú',
                'verbose_name_plural': 'Secciones de menú',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la novedad', max_length=255)),
                ('content', models.TextField(help_text='Contenido de la novedad')),
                ('image', models.FileField(blank=True, help_text='Imagen opcional para la novedad', null=True, upload_to='novelties')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la novedad está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'indexes': [models.Index(fields=['created_at'], name='app_managem_created_de2d80_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del módulo', max_length=100)),
                ('url_name', models.CharField(help_text="Nombre de la URL (ej. 'business_intelligence:sales_dashboard')", max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición dentro de la sección')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el módulo está activo')),
                ('allowed_groups', models.ManyToManyField(help_text='Grupos permitidos para acceder al módulo', related_name='accessible_modules', to='auth.group')),
                ('section', models.ForeignKey(help_text='Sección a la que pertenece el módulo', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app_management.menusection')),
            ],
            options={
                'verbose_name': 'Módulo del sistema',
                'verbose_name_plural': 'Módulos del sistema',
                'ordering': ['section__order', 'order'],
            },
        ),
    ]
