# Generated by Django 6.0.5 on 2026-07-24 02:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Característica que describe y diferencia al producto (ej. presentación, color), convirtiéndolo en una variante.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción opcional del atributo')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la categoría', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Nombre de la categoría', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción detallada de la categoría', max_length=500)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.CharField(help_text='Identificador del centro de distribución', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del centro de distribución', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('warehouse', 'almacén'), ('retail', 'tienda'), ('transfer', 'traspaso'), ('damaged', 'dañado/merma')], default='warehouse', help_text='Tipo de centro de distribución', max_length=20)),
            ],
            options={
                'verbose_name': 'Centro de distribución',
                'verbose_name_plural': 'Centros de distribución',
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la clase', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Nombre de la clase', max_length=255, null=True)),
                ('product_category', models.ForeignKey(blank=True, help_text='Categoría a la que pertenece esta clase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_product_classes', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Clase de producto',
                'verbose_name_plural': 'Clases de producto',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='Identificador único del producto', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Nombre general del producto', max_length=255, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Propiedades del producto')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está activo')),
                ('product_class', models.ForeignKey(blank=True, help_text='Clase a la que pertenece el producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_products', to='inventory.productclass')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la variante (ej. SKU)', max_length=50, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, help_text='Código de barras (UPC/EAN)', max_length=50, null=True)),
                ('external_id', models.CharField(blank=True, help_text='Identificador en sistemas externos (ej. ERP, eCommerce, proveedor)', max_length=50, null=True)),
                ('name', models.CharField(blank=True, help_text='Nombre específico de la variante', max_length=255, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Propiedades funcionales o intrínsecas (ej. especie destino, calorías). Describen la función, no lo que lo hace una variante. Varias variantes pueden compartir las mismas propiedades. No confundir con los atributos.')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la variante está activa')),
                ('product', models.ForeignKey(help_text='Producto base de esta variante', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_product_variants', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.CharField(help_text='Identificador único del lote (ej. BATCH-2026-001)', max_length=50, primary_key=True, serialize=False)),
                ('lot', models.CharField(blank=True, help_text='Número/Código de lote impreso por proveedor', max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de caducidad', null=True)),
                ('manufacturing_date', models.DateField(blank=True, help_text='Fecha de fabricación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del lote')),
                ('variant', models.ForeignKey(help_text='Variante de producto asociada a este lote', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_batches', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'unique_together': {('variant', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad en existencia', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización de la existencia')),
                ('batch', models.ForeignKey(help_text='Lote con dicha existencia', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_stocks', to='inventory.batch')),
                ('warehouse', models.ForeignKey(help_text='Centro de distribución con dicha existencia', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_stocks', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'unique_together': {('warehouse', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('fix_in', 'Ajuste positivo'), ('fix_out', 'Ajuste negativo')], default='in', help_text='Indica si el movimiento suma, resta o ajusta el inventario', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad (siempre positiva)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, help_text='Referencia (ej. Folio de compra, Factura, Venta)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del movimiento')),
                ('stock', models.ForeignKey(help_text='Registro de existencia que recibe el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_movements', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Movimiento de existencia',
                'verbose_name_plural': 'Movimientos de existencias',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Valor del atributo para esta variante (ej. Rojo, 500ml)', max_length=100)),
                ('attribute', models.ForeignKey(help_text='Atributo asignado', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_variant_attributes', to='inventory.attribute')),
                ('variant', models.ForeignKey(help_text='Variante a la que se le asigna el atributo', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_variant_attributes', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Atributo de Variantes',
                'verbose_name_plural': 'Atributos de Variantes',
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
