# Generated by Django 6.0.5 on 2026-07-29 07:45

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Propiedades del producto', validators=[apps.inventory.models.validate_product_properties]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Propiedades funcionales o intrínsecas (ej. especie destino, calorías). Describen la función, no lo que lo hace una variante. Varias variantes pueden compartir las mismas propiedades. No confundir con los atributos.', validators=[apps.inventory.models.validate_variant_properties]),
        ),
    ]
