# Generated by Django 6.0.5 on 2026-07-24 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(help_text='Identificador único del departamento', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del departamento', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del departamento', null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(help_text='Identificador único del puesto', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del puesto', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del puesto', max_length=255, null=True)),
                ('department', models.ForeignKey(help_text='Departamento al que pertenece el puesto', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_positions', to='human_resources.department')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(help_text='Identificador único del colaborador', max_length=20, primary_key=True, serialize=False)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_direct_reports', to='human_resources.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_employees', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_employees', to='human_resources.position')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
