# Generated by Django 5.2.16 on 2026-08-03 23:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(help_text='Identificador único del departamento', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del departamento', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción del departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la habilidad', max_length=150, unique=True)),
                ('skill_type', models.CharField(choices=[('hard', 'Técnica'), ('soft', 'Blanda'), ('language', 'Idioma'), ('other', 'Otra')], default='hard', help_text='Clasificación general de la habilidad', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Definición o alcance de la habilidad', null=True)),
            ],
            options={
                'verbose_name': 'Habilidad / Competencia',
                'verbose_name_plural': 'Catálogo de Habilidades',
                'ordering': ['skill_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(help_text='Identificador único del puesto', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del puesto', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción del puesto')),
                ('hierarchy_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='Nivel jerárquico del puesto', max_length=20)),
                ('department', models.ForeignKey(help_text='Departamento al que pertenece el puesto', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='human_resources.department')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='PositionKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del indicador (ej. Cumplimiento de cuota de ventas)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Fórmula o método detallado de cálculo para medir el indicador')),
                ('unit', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('currency', 'Monto Moneda'), ('numeric', 'Cantidad / Conteo'), ('boolean', 'Cumplimiento (Sí/No)'), ('rating', 'Escala / Calificación')], default='percentage', help_text='Unidad de medida del KPI', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Meta u objetivo a alcanzar para este puesto', max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ponderación o peso relativo del KPI sobre la evaluación total (0 a 100%)', max_digits=5)),
                ('frequency', models.CharField(choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='1m', help_text='Frecuencia con la que se debe evaluar este KPI', max_length=20)),
                ('position', models.ForeignKey(help_text='Puesto al que pertenece este indicador', on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='human_resources.position')),
            ],
            options={
                'verbose_name': 'KPI de Puesto',
                'verbose_name_plural': 'KPIs del Puesto',
                'ordering': ['position', '-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PositionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_level', models.CharField(choices=[('required', 'Requerido'), ('optional', 'Opcional'), ('preferred', 'Preferente')], default='required', help_text='Grado de obligatoriedad', max_length=20)),
                ('skill_level', models.CharField(choices=[('none', 'Sin conocimiento'), ('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='basic', help_text='Nivel de dominio mínimo requerido', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Especificaciones adicionales para este puesto (ej. Certificación vigente requerida)')),
                ('position', models.ForeignKey(help_text='Puesto al que se le asigna la competencia', on_delete=django.db.models.deletion.CASCADE, related_name='position_skills', to='human_resources.position')),
                ('skill', models.ForeignKey(help_text='Habilidad del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='position_requirements', to='human_resources.skill')),
            ],
            options={
                'verbose_name': 'Requisito de competencia',
                'verbose_name_plural': 'Requisitos de competencias',
                'unique_together': {('position', 'skill')},
            },
        ),
    ]
