# Generated by Django 6.0.5 on 2026-07-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la habilidad', max_length=150, unique=True)),
                ('skill_type', models.CharField(choices=[('hard', 'Técnica'), ('soft', 'Blanda'), ('language', 'Idioma'), ('other', 'Otra')], default='hard', help_text='Clasificación general de la habilidad', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Definición o alcance de la habilidad', null=True)),
            ],
            options={
                'verbose_name': 'Habilidad / Competencia',
                'verbose_name_plural': 'Catálogo de Habilidades',
                'ordering': ['skill_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PositionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_level', models.CharField(choices=[('required', 'Requerido'), ('optional', 'Opcional'), ('preferred', 'Preferente')], default='required', help_text='Grado de obligatoriedad', max_length=20)),
                ('skill_level', models.CharField(choices=[('none', 'Sin conocimiento'), ('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='basic', help_text='Nivel de dominio mínimo requerido', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Especificaciones adicionales para este puesto (ej. Certificación vigente requerida)', null=True)),
                ('position', models.ForeignKey(help_text='Puesto al que se le asigna la competencia', on_delete=django.db.models.deletion.CASCADE, related_name='position_skills', to='human_resources.position')),
                ('skill', models.ForeignKey(help_text='Habilidad del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='position_requirements', to='human_resources.skill')),
            ],
            options={
                'verbose_name': 'Requisito de competencia',
                'verbose_name_plural': 'Requisitos de competencias',
                'unique_together': {('position', 'skill')},
            },
        ),
    ]
