# Generated by Django 5.2.16 on 2026-08-04 01:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringForm',
            fields=[
                ('id', models.CharField(help_text='Identificador único del formulario', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del formulario', max_length=255)),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del formulario')),
                ('periodicity', models.CharField(choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='1w', help_text='Periodicidad del formulario', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el formulario está activo')),
            ],
            options={
                'verbose_name': 'Reporte de desempeño',
                'verbose_name_plural': 'Reportes de desempeño',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Pregunta o texto que ve el usuario', max_length=500)),
                ('response_type', models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número / Cantidad'), ('percentage', 'Porcentaje (%)'), ('scale_1_5', 'Escala 1 a 5'), ('boolean', 'Sí / No'), ('file', 'Archivo')], default='text', help_text='Tipo de respuesta', max_length=20)),
                ('description', models.TextField(blank=True, db_default='', help_text='Ayuda o guía para responder la pregunta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el campo está activo')),
            ],
            options={
                'verbose_name': 'Campo de reporte de desempeño',
                'verbose_name_plural': 'Campos de reportes de desempeño',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.CharField(help_text='Identificador único (ej. cdmx1, gdl, foráneos)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la gerencia o unidad de negocio', max_length=255)),
                ('parent', models.ForeignKey(blank=True, help_text='Gerencia padre (ej. Foráneos es padre de Culiacán, Colima, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='human_resources.businessunit')),
            ],
            options={
                'verbose_name': 'Unidad de Negocio / Gerencia',
                'verbose_name_plural': 'Unidades de Negocio / Gerencias',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(help_text='Identificador único del colaborador', max_length=20, primary_key=True, serialize=False)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('temporary', 'Temporal'), ('indeterminate', 'Indeterminado'), ('service', 'Servicios Profesionales / Honorarios'), ('internship', 'Prácticas / Becario'), ('other', 'Otro')], default='indeterminate', help_text='Tipo de contrato', max_length=20)),
                ('contract_doc', models.FileField(blank=True, help_text='Documento del contrato', null=True, upload_to='contracts')),
                ('tax_doc', models.FileField(blank=True, help_text='Documento de impuestos', null=True, upload_to='tax_docs')),
                ('tax_regime', models.CharField(choices=[('601', '601 General de Ley Personas Morales'), ('603', '603 Personas Morales con Fines no Lucrativos'), ('605', '605 Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 Arrendamiento'), ('607', '607 Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 Demás ingresos'), ('610', '610 Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 Ingresos por Dividendos (socios y accionistas)'), ('612', '612 Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 Ingresos por intereses'), ('615', '615 Régimen de los ingresos por obtención de premios'), ('616', '616 Sin obligaciones fiscales'), ('620', '620 Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 Incorporación Fiscal (RIF)'), ('622', '622 Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras (AGAPES)'), ('623', '623 Opcional para Grupos de Sociedades'), ('624', '624 Coordinados'), ('625', '625 Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 Régimen Simplificado de Confianza (RESICO)')], default='605', help_text='Régimen fiscal del colaborador (asociado a pago o facturación)', max_length=3)),
                ('tax_id', models.CharField(default='XAXX010101000', help_text='RFC del colaborador', max_length=13)),
                ('payment_form', models.CharField(choices=[('01', '01 Efectivo'), ('02', '02 Cheque nominativo'), ('03', '03 Transferencia electrónica de fondos'), ('04', '04 Tarjeta de crédito'), ('05', '05 Monedero electrónico'), ('06', '06 Dinero electrónico'), ('08', '08 Vales de despensa'), ('12', '12 Dación en pago'), ('13', '13 Pago por subrogación'), ('14', '14 Pago por consignación'), ('15', '15 Condonación'), ('17', '17 Compensación'), ('23', '23 Novación'), ('24', '24 Confusión'), ('25', '25 Remisión de deuda'), ('26', '26 Prescripción o caducidad'), ('27', '27 A satisfacción del acreedor'), ('28', '28 Tarjeta de débito'), ('29', '29 Tarjeta de servicios'), ('30', '30 Aplicación de anticipos'), ('31', '31 Intermediario pagos'), ('99', '99 Por definir')], default='99', help_text='Forma de pago al colaborador', max_length=2)),
                ('payroll_payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del pago al colaborador', max_digits=10)),
                ('payroll_frequency', models.CharField(choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='2w', help_text='Periodicidad del pago al colaborador', max_length=3)),
                ('business_unit', models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece el colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='human_resources.businessunit')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='human_resources.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='human_resources.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.AddField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Gerente de la unidad de negocio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_business_units', to='human_resources.employee'),
        ),
        migrations.CreateModel(
            name='MonitoringFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Nivel jerárquico al que se le asigna la pregunta', max_length=20, null=True)),
                ('order', models.IntegerField(default=1, help_text='Orden en el que se muestra la pregunta')),
                ('is_required', models.BooleanField(default=True, help_text='Indica si la pregunta es requerida')),
                ('form', models.ForeignKey(help_text='Formulario al que se le asigna la pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='human_resources.monitoringform')),
                ('position', models.ForeignKey(blank=True, help_text='Puesto al que se le asigna la pregunta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_form_questions', to='human_resources.position')),
                ('question', models.ForeignKey(help_text='Pregunta que se le asigna al formulario', on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='human_resources.monitoringformfield')),
            ],
            options={
                'verbose_name': 'Asignación de campo en reporte de desempeño',
                'verbose_name_plural': 'Asignaciones de campos en reportes de desempeño',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_identifier', models.CharField(help_text='Identificador del período (ej. 2026-W30 o 2026-07)', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('reviewed', 'Revisado')], default='draft', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_submissions', to='human_resources.employee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='human_resources.monitoringform')),
            ],
            options={
                'verbose_name': 'Envío de reporte de desempeño',
                'verbose_name_plural': 'Envíos de reportes de desempeño',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='Respuesta del usuario guardada de forma estructurada')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='human_resources.monitoringformquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='human_resources.monitoringformsubmission')),
            ],
            options={
                'verbose_name': 'Respuesta de reporte de desempeño',
                'verbose_name_plural': 'Respuestas de reportes de desempeño',
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('termination_date__isnull', True)), fields=('user', 'position'), name='unique_active_user_position_pair'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringformsubmission',
            unique_together={('employee', 'form', 'period_identifier')},
        ),
    ]
