# Generated by Django 5.2.16 on 2026-08-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_monitoringform_monitoringformfield_businessunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringFormSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_day', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=4, help_text='Día de la semana en que se abre el formulario')),
                ('open_time', models.TimeField(default='16:00:00', help_text='Hora exacta de apertura (ej. 16:00)')),
                ('duration_hours', models.PositiveIntegerField(default=48, help_text='Duración en horas del plazo de entrega (ej. 48 para que cierre el domingo a la misma hora)')),
                ('form', models.OneToOneField(help_text='Formulario asociado', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='human_resources.monitoringform')),
            ],
            options={
                'verbose_name': 'Programación de reporte de desempeño',
                'verbose_name_plural': 'Programaciones de reportes de desempeño',
            },
        ),
        migrations.CreateModel(
            name='MonitoringPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Identificador legible (ej. 2026-Semana30)', max_length=50)),
                ('start_date', models.DateTimeField(help_text='Fecha y hora exacta de inicio del plazo')),
                ('end_date', models.DateTimeField(help_text='Fecha y hora exacta de fin del plazo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este periodo está vigente/activo')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='human_resources.monitoringform')),
            ],
            options={
                'verbose_name': 'Periodo de evaluación',
                'verbose_name_plural': 'Periodos de evaluaciones',
                'unique_together': {('form', 'identifier')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='monitoringformsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monitoringformsubmission',
            name='period',
            field=models.ForeignKey(help_text='Periodo al que corresponde este envío', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='human_resources.monitoringperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringformsubmission',
            unique_together={('employee', 'form', 'period')},
        ),
        migrations.RemoveField(
            model_name='monitoringformsubmission',
            name='period_identifier',
        ),
    ]
