# Generated by Django 6.0.5 on 2026-07-27 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_skill_positionskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_doc',
            field=models.FileField(blank=True, help_text='Documento del contrato', null=True, upload_to='contracts'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('temporary', 'Temporal'), ('indeterminate', 'Indeterminado'), ('service', 'Servicios Profesionales / Honorarios'), ('internship', 'Prácticas / Becario'), ('other', 'Otro')], default='indeterminate', help_text='Tipo de contrato', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_doc',
            field=models.FileField(blank=True, help_text='Documento de impuestos', null=True, upload_to='tax_docs'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_id',
            field=models.CharField(default='XAXX010101000', help_text='RFC del colaborador', max_length=13),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.CharField(choices=[('601', '601 General de Ley Personas Morales'), ('603', '603 Personas Morales con Fines no Lucrativos'), ('605', '605 Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 Arrendamiento'), ('607', '607 Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 Demás ingresos'), ('610', '610 Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 Ingresos por Dividendos (socios y accionistas)'), ('612', '612 Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 Ingresos por intereses'), ('615', '615 Régimen de los ingresos por obtención de premios'), ('616', '616 Sin obligaciones fiscales'), ('620', '620 Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 Incorporación Fiscal (RIF)'), ('622', '622 Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras (AGAPES)'), ('623', '623 Opcional para Grupos de Sociedades'), ('624', '624 Coordinados'), ('625', '625 Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 Régimen Simplificado de Confianza (RESICO)')], default='605', help_text='Régimen fiscal del colaborador (asociado a pago o facturación)', max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_employees', to='human_resources.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
