# Generated by Django 5.2.16 on 2026-08-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_monitoringformschedule_monitoringperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringformschedule',
            name='week_of_month',
            field=models.CharField(choices=[('first', 'Primera'), ('second', 'Segunda'), ('third', 'Tercera'), ('fourth', 'Cuarta'), ('last', 'Última'), ('every', 'Todas (Para semanales)')], default='every', help_text='Semana del mes en la que aplica (útil para mensuales)', max_length=10),
        ),
    ]
