# Generated by Django 6.0.5 on 2026-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_employee_contract_doc_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='hierarchy_level',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], default='1', help_text='Nivel jerárquico del puesto', max_length=20),
        ),
    ]
