# Generated by Django 6.0.5 on 2026-08-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_monitoringformschedule_week_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='business_unit_type',
            field=models.CharField(choices=[('unit', 'Unidad'), ('region', 'Región')], db_index=True, default='unit', help_text='Tipo de unidad de negocio', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Gerente o responsable de la unidad de negocio / región', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_business_units', to='human_resources.employee'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Gerencia o región padre (ej. Foráneos es padre de Culiacán, Colima, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='human_resources.businessunit'),
        ),
    ]
