# Generated by Django 6.0.5 on 2026-07-27 06:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_position_hierarchy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_form',
            field=models.CharField(choices=[('01', '01 Efectivo'), ('02', '02 Cheque nominativo'), ('03', '03 Transferencia electrónica de fondos'), ('04', '04 Tarjeta de crédito'), ('05', '05 Monedero electrónico'), ('06', '06 Dinero electrónico'), ('08', '08 Vales de despensa'), ('12', '12 Dación en pago'), ('13', '13 Pago por subrogación'), ('14', '14 Pago por consignación'), ('15', '15 Condonación'), ('17', '17 Compensación'), ('23', '23 Novación'), ('24', '24 Confusión'), ('25', '25 Remisión de deuda'), ('26', '26 Prescripción o caducidad'), ('27', '27 A satisfacción del acreedor'), ('28', '28 Tarjeta de débito'), ('29', '29 Tarjeta de servicios'), ('30', '30 Aplicación de anticipos'), ('31', '31 Intermediario pagos'), ('99', '99 Por definir')], default='99', help_text='Forma de pago al colaborador', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_frequency',
            field=models.CharField(choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='2w', help_text='Periodicidad del pago al colaborador', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del pago al colaborador', max_digits=10),
        ),
    ]
