# Generated by Django 6.0.5 on 2026-07-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_employee_payment_form_employee_payroll_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionskill',
            name='position',
            field=models.ForeignKey(help_text='Puesto al que se le asigna la competencia', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_position_skills', to='human_resources.position'),
        ),
        migrations.AlterField(
            model_name='positionskill',
            name='skill',
            field=models.ForeignKey(help_text='Habilidad del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_position_requirements', to='human_resources.skill'),
        ),
    ]
