# Generated by Django 6.0.5 on 2026-07-28 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_alter_positionskill_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('termination_date__isnull', True)), fields=('user', 'position'), name='unique_active_user_position_pair'),
        ),
    ]
