# Generated by Django 6.0.5 on 2026-07-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_employee_unique_active_user_position_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.CharField(help_text='Identificador único (ej. cdmx1, gdl, foráneos)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la gerencia o unidad de negocio', max_length=255)),
                ('manager', models.ForeignKey(blank=True, help_text='Gerente de la unidad de negocio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_managed_business_units', to='human_resources.employee')),
                ('parent', models.ForeignKey(blank=True, help_text='Gerencia padre (ej. Foráneos es padre de Culiacán, Colima, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_sub_units', to='human_resources.businessunit')),
            ],
            options={
                'verbose_name': 'Unidad de Negocio / Gerencia',
                'verbose_name_plural': 'Unidades de Negocio / Gerencias',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de negocio a la que pertenece el colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_employees', to='human_resources.businessunit'),
        ),
    ]
