# Generated by Django 6.0.5 on 2026-07-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_businessunit_employee_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringForm',
            fields=[
                ('id', models.CharField(help_text='Identificador único del formulario', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del formulario', max_length=255)),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del formulario')),
                ('periodicity', models.CharField(choices=[('1d', '1 día'), ('1w', '1 semana'), ('2w', '2 semanas'), ('1m', '1 mes'), ('2m', '2 meses'), ('3m', '3 meses'), ('4m', '4 meses'), ('5m', '5 meses'), ('6m', '6 meses'), ('7m', '7 meses'), ('8m', '8 meses'), ('9m', '9 meses'), ('10m', '10 meses'), ('11m', '11 meses'), ('1y', '1 año')], default='1w', help_text='Periodicidad del formulario', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el formulario está activo')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Pregunta o texto que ve el usuario', max_length=500)),
                ('response_type', models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número / Cantidad'), ('percentage', 'Porcentaje (%)'), ('scale_1_5', 'Escala 1 a 5'), ('boolean', 'Sí / No')], default='text', help_text='Tipo de respuesta', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Ayuda o guía para responder la pregunta', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el campo está activo')),
            ],
            options={
                'verbose_name': 'Campo de formulario de monitoreo',
                'verbose_name_plural': 'Campos de formulario de monitoreo',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_level', models.CharField(blank=True, choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], help_text='Nivel jerárquico al que se le asigna la pregunta', max_length=20, null=True)),
                ('order', models.IntegerField(default=1, help_text='Orden en el que se muestra la pregunta')),
                ('is_required', models.BooleanField(default=True, help_text='Indica si la pregunta es requerida')),
                ('form', models.ForeignKey(help_text='Formulario al que se le asigna la pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_form_questions', to='human_resources.monitoringform')),
                ('position', models.ForeignKey(blank=True, help_text='Puesto al que se le asigna la pregunta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_monitoring_form_questions', to='human_resources.position')),
                ('question', models.ForeignKey(help_text='Pregunta que se le asigna al formulario', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_form_questions', to='human_resources.monitoringformfield')),
            ],
            options={
                'verbose_name': 'Pregunta de formulario de monitoreo',
                'verbose_name_plural': 'Preguntas de formulario de monitoreo',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_identifier', models.CharField(help_text='Identificador del período (ej. 2026-W30 o 2026-07)', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('reviewed', 'Revisado')], default='draft', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_monitoring_submissions', to='human_resources.employee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_submissions', to='human_resources.monitoringform')),
            ],
            options={
                'verbose_name': 'Envío de formulario de monitoreo',
                'verbose_name_plural': 'Envíos de formularios de monitoreo',
                'unique_together': {('employee', 'form', 'period_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='Respuesta del usuario guardada de forma estructurada')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_answers', to='human_resources.monitoringformquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_answers', to='human_resources.monitoringformsubmission')),
            ],
            options={
                'verbose_name': 'Respuesta de formulario de monitoreo',
                'verbose_name_plural': 'Respuestas de formularios de monitoreo',
            },
        ),
    ]
