# Generated by Django 6.0.5 on 2026-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_monitoringform_monitoringformfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringformfield',
            name='response_type',
            field=models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número / Cantidad'), ('percentage', 'Porcentaje (%)'), ('scale_1_5', 'Escala 1 a 5'), ('boolean', 'Sí / No'), ('file', 'Archivo')], default='text', help_text='Tipo de respuesta', max_length=20),
        ),
    ]
