"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()


MONTHS = {
            1: 'Enero',
            2: 'Febrero',
            3: 'Marzo',
            4: 'Abril',
            5: 'Mayo',
            6: 'Junio',
            7: 'Julio',
            8: 'Agosto',
            9: 'Septiembre',
            10: 'Octubre',
            11: 'Noviembre',
            12: 'Diciembre'
        }

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    'datall.angel-velasco.com',
    '192.168.100.114',
    '127.0.0.1' ,
    'datall.com.mx',
    'www.datall.com.mx',
    'urvet.datall.com.mx',
    'www.urvet.datall.com.mx'

]
CSRF_TRUSTED_ORIGINS = [
    'https://datall.angel-velasco.com',
    'https://datall.com.mx',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_FAILURE_VIEW = 'apps.core.views.custom_csrf_failure'

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # for r2 storages
    'storages',

    'apps.core',
    'apps.business_intelligence',
    'apps.sales',
    'apps.customers',
    'apps.marketing',
    'apps.human_resources',
    'apps.data_admin',
    'apps.data_assistant'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #get allowed modules for users
                'apps.core.context_processors.module_permissions',
                #get last update of data
                'apps.core.context_processors.last_update',
                #get last app version
                'apps.core.context_processors.get_app_version',
                #get recent novelties (last week)
                'apps.core.context_processors.recent_novelties',
                # media files
                'django.template.context_processors.media',                
            ],
        },
    },
]

LOGIN_REDIRECT_URL = '/business_intelligence/sales_dashboard'

LOGOUT_REDIRECT_URL = '/accounts/login/'

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": ["redis://127.0.0.1:6379/0"],
        },
    },
}

AUTH_USER_MODEL = 'core.User'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_DEBUG_NAME'),
            'USER': os.getenv('DB_DEBUG_USER'),
            'PASSWORD': os.getenv('DB_DEBUG_PASSWORD'),
            'HOST': os.getenv('DB_DEBUG_HOST'),
            'PORT': os.getenv('DB_DEBUG_PORT'),
        }
    }

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }

    # Cloudflare R2 / S3 Config
    AWS_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL')

    AWS_S3_CUSTOM_DOMAIN = 'media.datall.com.mx'
    AWS_QUERYSTRING_AUTH = False 
    AWS_DEFAULT_ACL = None

    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "media",
            }
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            'OPTIONS': {
                'location': 'static'
            }
        },
    }
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


MEDIA_ROOT = BASE_DIR / 'media'



#email sending config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = os.getenv('RESEND_API_KEY')

DEFAULT_FROM_EMAIL = 'Datall <no-reply@datall.com.mx>'
RESET_PASSWORD_FROM_EMAIL = 'Datall <reset-password@datall.com.mx>'
HR_FROM_EMAIL = 'Datall <rh@datall.com.mx>'
DATA_ANALYST_FROM_EMAIL = 'Datall <analisis@datall.com.mx>'
COMMERCIAL_FROM_EMAIL = 'Datall <comercial@datall.com.mx>'
MARKETING_FROM_EMAIL = 'Datall <marketing@datall.com.mx>'
SUPPORT_FROM_EMAIL = 'angel.emma.velasco@gmail.com'





ACCESS_DENIED_TEMPLATE = 'errors/access_denied.html'
PAGE_NOT_FOUND_TEMPLATE = 'errors/404.html'


