from django.urls import path
from .views import (
    customer_list_view,
    customer_create_view,
    customer_detail_view,
    customer_update_view,
    customer_add_note_view,
    customer_add_contact_view,
    customer_update_contact_view,
    customer_delete_contact_view,
    customer_filter_options_view,
    ar_list_view,
    ar_detail_view,
    export_ars_view,
    customer_agreement_list_view,
    customer_agreement_detail_view,
    customer_agreement_create_view,
    customer_agreement_validate_margin_view,
    customer_agreement_preview_view,
    customer_agreement_search_customers_view,
    customer_agreement_update_document_view,
    customer_agreement_evaluate_action_view,
    customer_options_view,
)

app_name = 'customers'

urlpatterns = [
    path('customers/options/', customer_options_view, name='customer_options_view'),
    path('filter-options/', customer_filter_options_view, name='customer_filter_options_view'),
    path('customers/', customer_list_view, name='customer_list_view'),
    path('customers/create/', customer_create_view, name='customer_create_view'),
    path('customers/<str:pk>/', customer_detail_view, name='customer_detail_view'),
    path('customers/<str:pk>/update/', customer_update_view, name='customer_update_view'),
    path('customers/<str:pk>/notes/add/', customer_add_note_view, name='customer_add_note_view'),
    path('customers/<str:pk>/contacts/add/', customer_add_contact_view, name='customer_add_contact_view'),
    path('customers/<str:pk>/contacts/<int:contact_id>/update/', customer_update_contact_view, name='customer_update_contact_view'),
    path('customers/<str:pk>/contacts/<int:contact_id>/delete/', customer_delete_contact_view, name='customer_delete_contact_view'),
    path('accounts-receivable/', ar_list_view, name='ar_list_view'),
    path('accounts-receivable/export/', export_ars_view, name='export_ars_view'),
    path('accounts-receivable/<str:pk>/', ar_detail_view, name='ar_detail_view'),
    
    path('agreements/', customer_agreement_list_view, name='customer_agreement_list_view'),
    path('agreements/create/', customer_agreement_create_view, name='customer_agreement_create_view'),
    path('agreements/validate-margin/', customer_agreement_validate_margin_view, name='customer_agreement_validate_margin_view'),
    path('agreements/preview/', customer_agreement_preview_view, name='customer_agreement_preview_view'),
    path('agreements/search-customers/', customer_agreement_search_customers_view, name='customer_agreement_search_customers_view'),
    path('agreements/<int:pk>/', customer_agreement_detail_view, name='customer_agreement_detail_view'),
    path('agreements/<int:pk>/document/', customer_agreement_update_document_view, name='customer_agreement_update_document_view'),
    path('agreements/<int:pk>/evaluate/', customer_agreement_evaluate_action_view, name='customer_agreement_evaluate_action_view'),
]