# Generated by Django 5.2.16 on 2026-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenueInegi',
            fields=[
                ('id', models.CharField(help_text='Identificador único de la unidad económica en INEGI', max_length=100, primary_key=True, serialize=False)),
                ('clee', models.CharField(blank=True, default='', help_text='Clave Estadística Empresarial (CLEE)', max_length=100)),
                ('unit_name', models.CharField(blank=True, db_index=True, default='', help_text='Nombre de la unidad económica', max_length=255)),
                ('tax_name', models.CharField(blank=True, default='', help_text='Razón social', max_length=255)),
                ('scian_code', models.CharField(db_index=True, help_text='Código de la clase de la actividad SCIAN', max_length=100)),
                ('scian_name', models.CharField(blank=True, default='', help_text='Nombre de clase de la actividad', max_length=255)),
                ('personal_occupied_stratum', models.CharField(blank=True, default='', help_text='Descripción estrato personal ocupado', max_length=100)),
                ('viality_type', models.CharField(blank=True, default='', help_text='Tipo de vialidad', max_length=100)),
                ('viality_name', models.CharField(blank=True, default='', help_text='Nombre de la vialidad', max_length=255)),
                ('cross_viality_type_1', models.CharField(blank=True, default='', help_text='Tipo de entre vialidad 1', max_length=100)),
                ('cross_viality_name_1', models.CharField(blank=True, default='', help_text='Nombre de entre vialidad 1', max_length=255)),
                ('cross_viality_type_2', models.CharField(blank=True, default='', help_text='Tipo de entre vialidad 2', max_length=100)),
                ('cross_viality_name_2', models.CharField(blank=True, default='', help_text='Nombre de entre vialidad 2', max_length=255)),
                ('cross_viality_type_3', models.CharField(blank=True, default='', help_text='Tipo de entre vialidad 3', max_length=100)),
                ('cross_viality_name_3', models.CharField(blank=True, default='', help_text='Nombre de entre vialidad 3', max_length=255)),
                ('external_number', models.CharField(blank=True, default='', help_text='Número exterior o kilómetro', max_length=100)),
                ('external_letter', models.CharField(blank=True, default='', help_text='Letra exterior', max_length=100)),
                ('building', models.CharField(blank=True, default='', help_text='Edificio', max_length=255)),
                ('building_floor', models.CharField(blank=True, default='', help_text='Edificio Piso', max_length=100)),
                ('internal_number', models.CharField(blank=True, default='', help_text='Número interior', max_length=100)),
                ('internal_letter', models.CharField(blank=True, default='', help_text='Letra interior', max_length=100)),
                ('settlement_type', models.CharField(blank=True, default='', help_text='Tipo de asentamiento humano', max_length=100)),
                ('settlement_name', models.CharField(blank=True, db_index=True, default='', help_text='Nombre de asentamiento humano', max_length=255)),
                ('shopping_center_type', models.CharField(blank=True, default='', help_text='Tipo centro comercial', max_length=100)),
                ('industrial_commercial_public_market', models.CharField(blank=True, default='', help_text='Corredor industrial, centro comercial o mercado público', max_length=255)),
                ('unit_number', models.CharField(blank=True, default='', help_text='Número de local', max_length=100)),
                ('zip_code', models.CharField(blank=True, db_index=True, default='', help_text='Código Postal', max_length=100)),
                ('state_code', models.CharField(db_index=True, help_text='Clave entidad', max_length=100)),
                ('state_name', models.CharField(blank=True, db_index=True, default='', help_text='Entidad federativa', max_length=255)),
                ('municipality_code', models.CharField(db_index=True, help_text='Clave municipio', max_length=100)),
                ('municipality_name', models.CharField(blank=True, db_index=True, default='', help_text='Municipio', max_length=255)),
                ('locality_code', models.CharField(blank=True, default='', help_text='Clave localidad', max_length=100)),
                ('locality_name', models.CharField(blank=True, default='', help_text='Localidad', max_length=255)),
                ('basic_geostatistical_area', models.CharField(blank=True, default='', help_text='Área geoestadística básica (AGEB)', max_length=100)),
                ('block', models.CharField(blank=True, default='', help_text='Manzana', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Número de teléfono', max_length=100)),
                ('email', models.CharField(blank=True, default='', help_text='Correo electrónico', max_length=255)),
                ('website', models.CharField(blank=True, default='', help_text='Sitio en Internet', max_length=255)),
                ('establishment_type', models.CharField(blank=True, default='', help_text='Tipo de establecimiento', max_length=100)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=9, help_text='Latitud', max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=9, help_text='Longitud', max_digits=12, null=True)),
                ('denue_incorporation_date', models.CharField(blank=True, default='', help_text='Fecha de incorporación al DENUE', max_length=100)),
            ],
            options={
                'verbose_name': 'Unidad Económica DENUE',
                'verbose_name_plural': 'Unidades Económicas DENUE',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='mapser_denu_latitud_48f4cd_idx'), models.Index(fields=['state_code', 'municipality_code'], name='mapser_denu_state_c_98899b_idx'), models.Index(fields=['scian_code', 'state_code'], name='mapser_denu_scian_c_a060bb_idx')],
            },
        ),
    ]
