# Generated by Django 5.2.16 on 2026-08-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_accountsreceivable_balance_15_and_more'),
        ('mapser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='', help_text='Calle y número exterior/interior', max_length=255)),
                ('neighborhood', models.CharField(blank=True, default='', help_text='Colonia o asentamiento', max_length=150)),
                ('municipality', models.CharField(blank=True, default='', help_text='Municipio o alcaldía', max_length=150)),
                ('state', models.CharField(blank=True, default='', help_text='Entidad federativa', max_length=100)),
                ('zip_code', models.CharField(blank=True, db_index=True, default='', help_text='Código Postal', max_length=10)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=9, help_text='Latitud', max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=9, help_text='Longitud', max_digits=12, null=True)),
                ('geocoding_source', models.CharField(choices=[('exact', 'Coordenadas GPS directas'), ('postal_code', 'Centroide de Código Postal'), ('manual', 'Ajuste manual en mapa'), ('unresolved', 'Sin resolver')], db_index=True, default='unresolved', help_text='Fuente / método utilizado para determinar las coordenadas', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si la ubicación fue verificada manualmente')),
                ('last_geocoded_at', models.DateTimeField(blank=True, help_text='Fecha y hora del último procesamiento geográfico', null=True)),
                ('customer', models.OneToOneField(help_text='Cliente vinculado a este perfil geográfico', on_delete=django.db.models.deletion.CASCADE, related_name='geo_profile', to='customers.customer')),
                ('matched_denue', models.ForeignKey(blank=True, help_text='Unidad económica del DENUE correspondiente a este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_customer_profiles', to='mapser.denueinegi')),
            ],
            options={
                'verbose_name': 'Perfil Geográfico de Cliente',
                'verbose_name_plural': 'Perfiles Geográficos de Clientes',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='mapser_cust_latitud_d4202a_idx'), models.Index(fields=['zip_code', 'geocoding_source'], name='mapser_cust_zip_cod_a7be93_idx')],
            },
        ),
    ]
